### ISSUE TITLE
Exceeded the maximum number of open cursors

### ISSUE THREAD

**Issue by chenxk** [apache/shardingsphere#10449]
500+ tables in my Oracle DB.
When the application running ,  an exception occurred: Exceeded the maximum number of open cursors

I found the problem at this class:
**org.apache.shardingsphere.sql.parser.binder.metadata.column.ColumnMetaDataLoader.load(final Connection connection, final String table, final String databaseType) throws SQLException**

----------Exception occurred -----------
try (ResultSet resultSet = connection.createStatement().executeQuery(generateEmptyResultSQL(table, databaseType))) {
    for (String each : columnNames) {
        isCaseSensitives.add(resultSet.getMetaData().isCaseSensitive(resultSet.findColumn(each)));
    }
}

**connection.createStatement()** , created a statement  ,but  do not close .

So i modified  code  as:

Statement statement = connection.createStatement();
    try (ResultSet resultSet = statement.executeQuery(generateEmptyResultSQL(table, databaseType))) {
        for (String each : columnNames) {
            isCaseSensitives.add(resultSet.getMetaData().isCaseSensitive(resultSet.findColumn(each)));
        }
    }
    statement.close();

Fixed the problem !!!

**Looking forward to your better solution。**

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

**Comment by tristaZero** [comment]
Hi @chenxk ,

Thanks for your report. 
I just gave a look at the [master branch](https://github.com/apache/shardingsphere/blob/master/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/schema/builder/loader/ColumnMetaDataLoader.java), and this issue still exists.
Would you like to help this community fix it for the master branch? If you like, [guide](https://shardingsphere.apache.org/community/cn/contribute/contributor/) will give you some hints. Otherwise, please still comment here so that I can call help from others.

**Comment by chenxk** [comment]
> Hi @chenxk ,
> 
> Thanks for your report.
> I just gave a look at the [master branch](https://github.com/apache/shardingsphere/blob/master/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/schema/builder/loader/ColumnMetaDataLoader.java), and this issue still exists.
> Would you like to help this community fix it for the master branch? If you like, [guide](https://shardingsphere.apache.org/community/cn/contribute/contributor/) will give you some hints. Otherwise, please still comment here so that I can call help from others.

OK， It's my pleasure。

**Comment by tristaZero** [comment]
#10471 fixed
