### ISSUE TITLE
Is there a Sharding-JDBC 5.0.0-alpha hint configuration demo

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#10952]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Is there a Sharding-JDBC 5.0.0-alpha hint configuration demo
For example：(This configuration reported an error)
spring.shardingsphere.rules.sharding.tables.<table-name>.database-strategy.hint.<myClassName>.sharding-algorithm-name=myClassName

**Comment by strongduanmu** [comment]
@monkeymada You can refer to the example module in the `shardingsphere` source code project, we provide `hint-example`.

**Comment by monkeymada** [comment]
Refer to the document configuration but always report an error:
Caused by: org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.sharding.spi.ShardingAlgorithm` with type `CLASS_BASED`.
Configuration details:

#sharding-jdbc
#spring.shardingsphere.datasource.names=ds1,ds2
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.common.username=admin
spring.shardingsphere.datasource.common.password=123456

spring.shardingsphere.datasource.ds1.jdbc-url=jdbc:mysql://localhost:3306/my_sql?serverTimezone=UTC&useSSL=false
spring.shardingsphere.datasource.ds2.jdbc-url=jdbc:mysql://localhost:3306/my_sql?serverTimezone=UTC&useSSL=false


# 用于Hint 的分片策略
spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=ds${1..2}.t_order

spring.shardingsphere.rules.sharding.tables.t_order.database-strategy.hint.hint-test.sharding-algorithm-name=hint-test

spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.type=CLASS_BASED
spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.props.strategy=HINT
spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.props.algorithmClassName=com.shardingjdbc.test.DatabaseHintShardingKeyAlgorithm

**Comment by strongduanmu** [comment]
@monkeymada Please try `5.0.0-beta` version.

**Comment by monkeymada** [comment]
Could you please help me to check where is my configuration wrong

**Comment by strongduanmu** [comment]
@monkeymada The CLASS_BASED configuration is a new feature added in the beta version, so it can only be used after an upgrade.

**Comment by monkeymada** [comment]
Please tell me how to configure the hint mode correctly in 5.0.0-alpha. Please tell me how to configure the hint mode correctly

**Comment by monkeymada** [comment]
Plan to use online, so want to use stable version
