### ISSUE TITLE
[Doc] Optimize change history of ShardingSphere-JDBC Spring Boot Starter Configuration (Chinese)

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10983]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972 

### Aim

Optimize change history of ShardingSphere-JDBC Spring Boot Starter Configuration. (Chinese version). 

### How to

1. Migrate ` Spring Boot Starter Configuration` change history from

   `4.1.2.Configuration Manual`->`Spring Boot Starter Configuration`->`Change History` to

   `7.2.API Change History`->`7.2.1.ShardingSphere-JDBC`->`Spring Boot Starter Configuration`;

2. Refer to the documents of each version on the official website, check whether the change history is correct, and fill in the missing parts.

3. The content organization of the change history is as follows:

   - ShardingSphere-5.0.0-beta
     - Sharding
     - Readwrite-splitting
     - Encryption
     - Shadow DB
     - Governance
   - ShardingSphere-4.x
     - Sharding
     - Readwrite-splitting
     - Data Masking
     - Orchestration
   - ShardingSphere-3.x
     - Sharding
     - Readwrite-splitting
     - Orchestration
   - ShardingSphere-2.x
     - Sharding
     - Readwrite-splitting
     - Orchestration

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [Spring Boot Starter Configuration change history](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/)

**Comment by donjuan6** [comment]
Can it be assigned to me？

**Comment by RaigorJiang** [comment]
Hi @donjuan6
Any progress?
If you don’t have time, can we assign to others?

**Comment by donjuan6** [comment]
Yes



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 10:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] [Doc] Optimize change history of ShardingSphere-JDBC Spring Boot Starter Configuration (Chinese) (#10983)




 
Hi @donjuan6
 Any progress?
 If you don’t have time, can we assign to others?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yx9o** [comment]
Please assign to me.
