### ISSUE TITLE
[Doc] add  configuration change history of ShardingSphere-Proxy (Chinese)

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10991]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

Add  configuration change history of ShardingSphere-Proxy. (Chinese version). 

### How to

1. Add  `7.2.2.ShardingSphere-Proxy` in the `7.2.API Change History` directory;
2. Create file `_index.cn.md` and write the configuration change history of proxy's `server.yaml`.

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [ShardingSphere-Proxy Configuration Manual](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/configuration/)

**Comment by donjuan6** [comment]
Can it be assigned to me？

**Comment by RaigorJiang** [comment]
Hi @donjuan6
Any progress?
If you don’t have time, can we assign to others?

**Comment by donjuan6** [comment]
Yes



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 10:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] [Doc] add  configuration change history of ShardingSphere-Proxy (Chinese) (#10991)




 
Hi @donjuan6
 Any progress?
 If you don’t have time, can we assign to others?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yx9o** [comment]
Please assign to me.
