### ISSUE TITLE
Improve DistSQL parser test engine with db-types 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11014]
The current DistSQL parser test engine using `db-types` to recognize DistSQL or normal SQL, which is not appropriate.

Please refactor here, decouple `db-types` and DistSQL.

**Comment by totalo** [comment]
Please assign it to me.

**Comment by terrymanu** [comment]
Cool, assigned

**Comment by totalo** [comment]
Hi, since distsql is now used as a db-type, this is not appropriate. In order to separate the plain SQL from distsql, my main idea is to use different XML tags, but the same set of XML parsers. Then, different SQL processing is performed based on different XML tags. As shown in the figure below:
![图](https://user-images.githubusercontent.com/29777558/124545122-04de4d80-de5b-11eb-8b3c-03eccd19b439.png)
