### ISSUE TITLE
Redesign JAXB domain of DistSQL

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11020]
- [x] Use xml attribute instead of xml element of ExpectedDataSource
- [x] Use xml attribute instead of xml element of ExpectedTableRule excepted tableStrategy and keyGenerateStrategy
- [x] Add `data-sources` tag for ExpectedTableRule.dataSources
- [x] Use xml attribute instead of xml element of ExpectedAlgorithm.name
- [x] use `data-source` instead of `dataSource` in xml tag
- [x] Please fill other changes need to do

**Comment by totalo** [comment]
Please assign it to me and I will fix this problem.

**Comment by terrymanu** [comment]
@totalo Sure

**Comment by totalo** [comment]
- [ ] Use xml attribute instead of xml element of ExceptedReadwriteSplittingRule
- [ ] Use xml attribute instead of xml element of ExpectedDatabaseDiscoveryRule excepted props and data-source
- [ ] Use xml attribute instead of xml element of ExpectedEncryptRule.name
- [ ] Use xml attribute instead of xml element of ExpectedShardingBindingTableRule.tableGroups
- [ ] The name of the canonical label
