### ISSUE TITLE
Add custom sharding algorithm example for shardingsphere-jdbc (by SPI)

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#11038]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Aim

Add an custom sharding algorithm example, which shows how to extend sharding algorithm by SPI.

### Basic Qualifications

- Java
- Maven

### Example FYI

`examples`->`shardingsphere-jdbc-example`->`extension-example`->

`custom-sharding-algortihm-example`

**Comment by donjuan6** [comment]
Can it be assigned to me？

**Comment by strongduanmu** [comment]
@donjuan6 Welcome.

**Comment by RaigorJiang** [comment]
Hi @donjuan6
Any progress?
If you don’t have time, can we assign to others?

**Comment by donjuan6** [comment]
Yes



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 10:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] Add custom sharding algorithm example for shardingsphere-jdbc (by SPI) (#11038)




 
Hi @donjuan6
 Any progress?
 If you don’t have time, can we assign to others?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
