### ISSUE TITLE
Add an auto sharding table example.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#11108]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Aim

Add an auto sharding table example with `ShardingAutoTableRuleConfiguration`. in [examples](https://github.com/apache/shardingsphere/tree/master/examples) project.

### Basic Qualifications

- Java
- Maven

### Example FYI

`examples`->`shardingsphere-jdbc-example`->`other-feature-example`.

Please add a new sub-module named `auto-table-example`.

### Notice

Please add at least one complete example of Java raw API. It would be better if you can provide examples of SpringBoot and Spring namespace.

### Reference

- https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/java-api/sharding/#sharding-automatic-table-configuration

- https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/yaml/sharding/

- https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/change-history/

**Comment by donjuan6** [comment]
Can it be assigned to me？

**Comment by RaigorJiang** [comment]
Hi @donjuan6
Any progress?
If you don’t have time, can we assign to others?

**Comment by donjuan6** [comment]
Yes



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 10:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] Add an auto sharding table example. (#11108)




 
Hi @donjuan6
 Any progress?
 If you don’t have time, can we assign to others?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RaigorJiang** [comment]
Due to the adjustment of the examples structure (#12557), example for autoTable should not be added to the other-example module.
The new location should be under `shardingsphere-jdbc-example/single-feature-example/sharding-example`, just add a new autoTable configuration example for each sub module.

**Comment by yx9o** [comment]
I want to try this issue.

**Comment by RaigorJiang** [comment]
@yx9o  Welcome.
