### ISSUE TITLE
PGSQL does not support DML operations in encrypt scenarios

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#11465]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Actual behavior
When I execute the statement on the encrypt column it reports error 'You have an error in your SQL syntax' 

### Reason analyze (If you can)
Temporarily not supported

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Recreate the environment through the [configuration file](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/docker/encrypt/postgresql/proxy/conf/config-encrypt.yaml) and [init.sql](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/env/encrypt/init-sql/postgresql) to execute statement `UPDATE t_user u SET u.status = 'update' WHERE u.pwd = 'a10'`

**Comment by strongduanmu** [comment]
@JiekerTime Refer to the official documentation, specifying table_name or alias in column_name is invalid. Therefore, the valid SQL should be `UPDATE t_user u SET status ='update' WHERE u.pwd ='a10'`.

Executing this valid SQL will still report an error because the PostgreSQL syntax is ambiguous for the alias `u`.
