### ISSUE TITLE
ShardingSphere Bean is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

### ISSUE THREAD

**Issue by Lacxner** [apache/shardingsphere#11650]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0Beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Example codes for reproduce this issue (such as a github link).
Console print Bean is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) where application bootstraps.
![1628085763(1)](https://user-images.githubusercontent.com/35280133/128194762-9df95006-f205-4524-9a61-a2dde1bdbcd3.png)
![1628085883(1)](https://user-images.githubusercontent.com/35280133/128195062-fea5b55d-dc67-4f50-a79a-4f4744e5001d.png)

**Comment by linghengqian** [comment]
Is anyone paying attention? While this information is mostly INFO, it does cause some confusion. (Sorry I can't help with this. 👀)

**Comment by linghengqian** [comment]
- There is a problem, ShardingSphere JDBC SpringBoot Starter is still using `spring-context-4.3.25.RELEASE` instead of `spring-context-5.x`, which causes `org.springframework.context.annotation.Configuration` not to exist `proxyBeanMethods` properties. 

- Considering issues like https://github.com/apache/shardingsphere/issues/20963 , I think we should drop ShardingSphere JDBC SpringBoot Starter support for SpringBoot OSS 1.X?

- ![image](https://user-images.githubusercontent.com/20187731/190887524-9a2abb0d-824b-4112-a9a3-7eb3a168c121.png)
- ![image](https://user-images.githubusercontent.com/20187731/190887628-9b6230df-da69-4672-a678-14a8139cffaa.png)

**Comment by linghengqian** [comment]
- I noticed that the git record actually used Spring Framework 5.x for a while, but was reverted.  I will be submitting a PR to drop support for Spring Boot OSS 1.X shortly.

**Comment by linghengqian** [comment]
- I just can't submit a PR right away due to personal matters.

**Comment by linghengqian** [comment]
- Found that I can't fully solve this problem locally, I'm not working on this issue.

**Comment by linghengqian** [comment]
- This issue should be marked as resolved and closed due to https://github.com/apache/shardingsphere/issues/22469 .

**Comment by RaigorJiang** [comment]
Closed for #22469.
