### ISSUE TITLE
the dependency of guava ，which is the Minimum Version Support？？？

### ISSUE THREAD

**Issue by xue2lang** [apache/shardingsphere#12656]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

i see the dependency of guava is 29.1-jre，I'm worried that the app is using a lower version，i want ask：what the guava Minimum Version Support？？？

**Comment by RaigorJiang** [comment]
Hi @xue2lang 
Why not tell us the version you are using first, and see if any one in the community have similar situations and can answer your questions?

**Comment by xue2lang** [comment]
@RaigorJiang The intercept version we are currently configuring is no less than 18.0 in the publishing system，This rule applies to all applications，but sharding client use the version of 29 ，Business applications may use lower versions in their project，So i ask is there a minimum version limit

**Comment by RaigorJiang** [comment]
@xue2lang 
May not be able to answer you clearly. Because ShardingSphere uses a variety of third-party components, they also have their own dependencies.
The more reliable methods are:
1. Check the update log of guava to confirm the change of 18.0-29.0;
2. Perform strict tests after integrating ShardingSphere to ensure that the features used meet expectations;
At the same time, like you, I look forward to other people’s better suggestions.

**Comment by xue2lang** [comment]
@RaigorJiang 3Q ，i will ry each version to see if any errors are reported

**Comment by RaigorJiang** [comment]
@xue2lang  You are welcome!
