### ISSUE TITLE
Can GitHub code be updated to gitee synchronously?

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12786]
Can GitHub code be updated to gitee synchronously?
At present, the code of gitee is not up-to-date. The speed of our connection to GitHub is too slow, and the phenomenon of clone failure will occur

**Comment by RaigorJiang** [comment]
![image](https://user-images.githubusercontent.com/5668787/135048445-fecadb20-0694-47a5-81c0-a6195126d3ab.png)
![image](https://user-images.githubusercontent.com/5668787/135048856-c91c9fac-3433-46b4-89e9-d27b794aafef.png)
![image](https://user-images.githubusercontent.com/5668787/135048917-6fb24617-4c23-445b-934a-a8ca26883720.png)


In gitee, you can create a repository by yourself and synchronize it from the github repository of ShardingSphere, so that you can get the latest code at any time.

**Comment by tristaZero** [comment]
Sorry, I still have no idea. I guess it's up to gitee, would you like to find some hints about gitee automated synchronization? If you have any answer, we'd like to provide any hands. I synchronized [ShardingSphere on gitee](https://gitee.com/Sharding-Sphere/sharding-sphere) just now by manual.

**Comment by RaigorJiang** [comment]
@tristaZero    This might help:
https://gitee.com/help/articles/4336#article-header3

**Comment by RaigorJiang** [comment]
@marker-wu @tristaZero 
I submitted an application for mirroring permission in gitee [link](https://gitee.com/gitee-community/mirror-repository), and now we need to wait for the follow-up progress.

**Comment by RaigorJiang** [comment]
Update: For the previous application, `Gitee` did not respond, I will continue to try to contact them.

**Comment by RaigorJiang** [comment]
Update: 
According to the latest information, only the bound account of the GiHub repository can set up automatic mirroring, and our repository belongs to the apache organization and cannot be processed through personal accounts. So the Gitee repository will still be synced manually.

Users can set up a GitHub repository by fork `apache/shardingsphere`, and then synchronize through Gitee, which can speed up the clone process.

**Comment by RaigorJiang** [comment]
I just close this issue.
