### ISSUE TITLE
Questions about the Hint strategy

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12945]
Is the Hint strategy supported only for single-table queries?

**Comment by strongduanmu** [comment]
Hint strategy is used for manual routing of sharding tables, single tables are not supported.

**Comment by marker-wu** [comment]
> Hint strategy is used for manual routing of sharding tables, single tables are not supported.
I use sharding-proxy for Hint routing test. Currently, the Hint policy for single-table query is effective, but the Hint policy for multi-table related queries does not take effect.

here are my configuration
![image](https://user-images.githubusercontent.com/45256940/136639286-de9e6f13-b909-4f91-af1a-ca66a4810ebf.png)

**Comment by marker-wu** [comment]
I use the latest master branch code, the project is ShardingSphere-Proxy
here are my configuration：
![image](https://user-images.githubusercontent.com/45256940/136639915-f3f8f11f-0170-4483-ac17-b6de60f3286b.png)
![image](https://user-images.githubusercontent.com/45256940/136639923-bc2a4d0e-47fa-4e97-8a3a-939344df5f63.png)

Steps: 1.set sharding hint database_value =1;
             2. select * from ak_log_template_config a,t_db b where a.id = b.id and id=1;
Execute this sql, the hint strategy does not take effect
when I execute the sql : select * from ak_log_template_config， the hint strategy  took effect
Result: Hint routing strategy is only effective for single-table query, not for multi-table query
Expected result: No matter what type of query, Hint routing strategy should be supported

**Comment by strongduanmu** [comment]
@marker-wu Thank you for your detailed information, I will check it.

**Comment by strongduanmu** [comment]
@marker-wu I checked the logic, because the `ak_log_template_config` and `t_db` tables are sharding tables and are distributed on different databases. Kernel cannot support this kind of cross-database query, so the sharding strategy that you are familiar with cannot be used. Currently, cross-database query is supported by the federation execution engine which is under development, and its implementation is completely different from the kernel.

Considering that your sharding tables all use the same sharding strategy, you can configure these two tables as binding tables, so that you can use the hint routing strategy.

**Comment by terrymanu** [comment]
I just close the issue because of no feedback for long time.
