### ISSUE TITLE
Shardingsphere-jdbc-5.0.0-bet PostgreSQL database coalesce cannot be used with count (distinct)

### ISSUE THREAD

**Issue by 1327681842** [apache/shardingsphere#13081]
eg:
select count(DISTINCT a) as a, coalesce(sum(b), 0) as b
from table_name
where c=? and d= ?

In this case, SQL can be executed in shardingsphere proxy, but an error is reported when using shardingsphere JDBC

**Comment by lanchengx** [comment]
Hi @1327681842 , thanks for your feedback, could you show the error log？

**Comment by strongduanmu** [comment]
> @strongduanmu I want check this issue.

@tuichenchuxin Good job, I have assign this issue to you.

**Comment by tuichenchuxin** [comment]
@1327681842 
When we use 
`select count(distinct a),sum(b) from table`
in sharding.
We'll get actual sql like `select distinct a,sum(b) from table_1`, Then it'll execute error.
So, This sql `select count(distinct a),sum(b) from table` is not supported by sharding.
This issue is not related to `coalesce` function.

**Comment by tuichenchuxin** [comment]
Closed due to no reply for a long time.
