### ISSUE TITLE
Add FAQ for DistSQL `ADD RESOURCE`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#13425]
### Background
DistSQL is a new feature of version 5.0. Users may encounter some error prompts when using it, but do not understand how to deal with these situations.

### Aim
Add FAQ, point out the cause of the error message, and provide solutions.

### How to
1. Understand the error message in the task description, investigate and confirm the cause. (Of course you can also ask for help)
2. Edit the [FAQ](https://github.com/apache/shardingsphere/tree/master/docs/document/content/reference/faq) files to add related questions and answers.  
3. If you are not good at Chinese, you can also submit an English FAQ independently.

### Task
-  ADD RESOURCE
 ```sql
mysql> ADD RESOURCE ds_0 (
    ->     HOST=127.0.0.1,
    ->     PORT=3306,
    ->     DB=demo_ds_0,
    ->     USER=root,
    ->     PASSWORD=123456,
    ->     PROPERTIES("maximumPoolSize"=10)
    -> );
ERROR 1104 (C1104): Can not process invalid resources, error messages are: [Invalid data source configuration name `ds_0`, error message is: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/demo_ds_0].
```

**Comment by Swastyy** [comment]
Hi @RaigorJiang Please assign this to me.

**Comment by Swastyy** [comment]
Hi @RaigorJiang This error shows that the variable DB is not the correct required argument for which the operation fails to get the URL for jdbc. Correct me if I am wrong. If that is the case then what should be the valid argument for which it will run?

**Comment by RaigorJiang** [comment]
@Swastyy 
The reason for 'Failed to get driver instance' is that Proxy did not have the jdbc driver during deployment, such as `mysql-connector`. You can try to reproduce this scenario.

**Comment by terrymanu** [comment]
We need to translate it to Chinese.
Any one what to try this task?

**Comment by yx9o** [comment]
> We need to translate it to Chinese. Any one what to try this task?

@terrymanu @RaigorJiang I can do it.

**Comment by RaigorJiang** [comment]
Thank you @yx9o .

**Comment by RaigorJiang** [comment]
Done, thank you all.

**Comment by wsm12138** [comment]
Hi~ @RaigorJiang  
###  Which version of ShardingSphere did you use? & Which project did you use?
I used 5.0.1 snapshot ShardingSphere-Proxy reproduce the problem（commit id:ec75ec41dfc70db6696b02282471ef0934a6f98c）
### Actual behavior 
When I  use DistSQL to add RESOURCE for DATABASE，the following error occurred.
![image](https://user-images.githubusercontent.com/86462784/147378121-2742b932-12e5-45b2-9a71-662c977d354a.png)
### Try to solve the problem 
I'm sure i have  `jdbc driver` because i can use `config-sharding.yaml` to startup Proxy successfuly
But i also can't find answer from [FAQ](https://github.com/apache/shardingsphere/blob/master/docs/document/content/reference/faq/_index.cn.md)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```yaml
[root@localhost conf]# cat server.yaml | grep -v "#"
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED

props:
```
Proxy
```shell
mysql -uroot -proot -h127.0.0.1 -P3307
mysql> create  database sbtest_sharding;
Query OK, 0 rows affected (0.99 sec)
mysql> use sbtest_sharding;
Database changed
mysql> ADD RESOURCE ds_0 (
    ->     HOST=127.0.0.1,
    ->     PORT=3306,
    ->     DB=sbtest_sharding,
    ->     USER=root,
    ->     PASSWORD=passwd
    -> ), ds_1 (
    ->     HOST=127.0.0.2,
    ->     PORT=3306,
    ->     DB=sbtest_sharding,
    ->     USER=root,
    ->     PASSWORD=passwd
    -> );
ERROR 1104 (C1104): Can not process invalid resources, error messages are: [Invalid data source configuration name `ds_0`, error message is: Failed to initialize pool: Communications link failure, Invalid data source configuration name `ds_1`, error message is: Failed to initialize pool: Communications link failure].
mysql> ^DBye
```
