### ISSUE TITLE
Add SkyWalking APM-SDK-plugin for ShardingSphere, to complete tracing context propagation

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#13764]
Hi community,

I am very happy to bring you good news that the [CyborgFlow](https://github.com/SphereEx/CyborgFlow) project has been officially available.

Welcome to download and use [release page](https://github.com/SphereEx/CyborgFlow/releases):

Many thanks to @mrproliu from SkyWalking and @tzssangglass from APISIX for their contributions.

But we cannot yet complete the support for the topology map because there is currently no tracer at the database level. 
We need a partner to participate in the development of the ShardingSphere plug-in.See [issues 8164](https://github.com/apache/skywalking/issues/8164) for details.

Refer to the development documentation of the plugin: [Java-Plugin-Development-Guide](https://github.com/apache/skywalking/blob/v8.7.0/docs/en/guides/Java-Plugin-Development-Guide.md) 

Plugin repository: [APM-SDK-plugin](https://github.com/apache/skywalking-java/tree/main/apm-sniffer/apm-sdk-plugin)

**Comment by wu-sheng** [comment]
Officially, I didn't cut the release, due to the announcement event has been cancelled considering COVID.

Back to this, if there is proxy-side plugin, ShardingSphere community should consider whether we should host the plugin by ourselves, rather than in SkyWalking repository. Because at there, we have to rely on their releasing period. Also, self-hosting means you could package the agent core and required plugins into your binary, users could be able to activate the agent by adding a system env or command argument.

Today, DolphinScheduler and Seata host the plugins(server-side mostly) on their own.

**Comment by tristaZero** [comment]
`proxy-side plugin` means the plugins provided by Skywalking and APISIX? So it is suggested to host these plugin coding on  CyborgFlow project?

**Comment by tristaZero** [comment]
I talked with @soulasuna to get the context of this issue. My +1 to let CyborgFlow host the plugin coding.

**Comment by wu-sheng** [comment]
> `proxy-side plugin` means the plugins provided by Skywalking and APISIX? So it is suggested to host these plugin coding on  CyborgFlow project?

You want to continue tracing to ShardingSphere proxy server, then you need a proxy. So where the codes hosting?

**Comment by wu-sheng** [comment]
Project open sourced here, https://github.com/SphereEx/CyborgFlow
A CN blog posted, https://skywalking.apache.org/zh/2022-01-18-cyborg-flow/

If anyone needs this blog in English, please let us know, we are glad to translate. Generally, this feature is requested in China community.
