### ISSUE TITLE
should throw ShardingSphereException while the SQL clause was not support in encrypt rule.

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#14248]
should throw ShardingSphereException while the SQL clause was not support in encrypt rule.

The SQL clause '%operator%' is unsupported in encrypt rule. 

For example, the operator ">" as below sql:

LogicSQL:
select t_account.certificate_number, t_account.amount, t_account_bak.certificate_number from t_account, t_account_bak where t_account.certificate_number = t_account_bak.certificate_number and t_account.amount > ?

ActualSQL:
select t_account.cipher_certificate_number AS certificate_number, t_account.cipher_amount AS amount, t_account_bak.cipher_certificate_number AS certificate_number from t_account, t_account_bak where t_account.assisted_query_certificate_number = t_account_bak.assisted_query_certificate_number and t_account.cipher_amount > ?

**Comment by strongduanmu** [comment]
Hi @cheese8, thank you very much for your issue, but I don’t think we should add this check, because some users of ShardingSphere have implemented the encryption algorithm by themselves, and the numerical value can still be a numerical 
 value after being encrypted. In this case, the encrypted field It is possible to perform `>` operations.
