### ISSUE TITLE
DML and BatchDML run together may throw exception in PG test if use WaitStrategy only

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15454]
DML and BatchDML run together may throw exception in PG test if use WaitStrategy only.

So we need to add execute() method to try to connect PG, it is better to remove it and use WaitStrategy only.

**Comment by shankeerthan-kasilingam** [comment]
Can I try this issue?

**Comment by yx9o** [comment]
@shankeerthan-kasilingam Welcome.

**Comment by menghaoranss** [comment]
@shankeerthan-kasilingam Nice to see you here again.

**Comment by shankeerthan-kasilingam** [comment]
I was able to reproduce the issue. The test suite fails to start the Containers that cause the PSQL connection error. Because our current wait Strategy relies on log messages. What happened is after logging “ready to accept the connection”, the test container throws an error that it failed to create container exceptions. I’m further analyzing it and I'll get back to you.

**Comment by TeslaCN** [comment]
We have improved WaitStrategy in https://github.com/apache/shardingsphere/pull/16153.
