### ISSUE TITLE
Any plans to use Gradle  instead of maven ？

### ISSUE THREAD

**Issue by misselvexu** [apache/shardingsphere#17197]
## Question

Any plans to use Gradle  instead of maven ？

**Comment by linghengqian** [comment]
I'm not sure what the community thinks, but I personally hate using a flexible scripting language like `Groovy` in a package manager (`Kotlin-DSL` is great by definition, of course, but it's a much more niche option). I prefer to use a rigorously defined markup language like `XML`, which is why `Maven` is so easy for developers to get started with. Furthermore, According to `Synk`, `Maven`'s market share (76%) is twice that of `Gradle`'s (38%), which I think is somewhat mainstream. Refer to https://snyk.io/jvm-ecosystem-report-2021/? utm_campaign=JVM-SC-2021&utm_medium=Report-Link#jvm-developers-use-maven

**Comment by TeslaCN** [comment]
Duplicated with https://github.com/apache/shardingsphere/issues/11573
