### ISSUE TITLE
Does shardingsphere-proxy support Oracle database? If not, is there any plan?

### ISSUE THREAD

**Issue by marsgooder** [apache/shardingsphere#17768]
Try to configure Oracle database using Sharingsphere Proxy, but errors occur as following pictures show: 

Shardingsphere Proxy release 5.1.1 stdout error:
![A9EF09C6-645F-474f-A872-C93B464BA5B7](https://user-images.githubusercontent.com/20876027/168948568-5c171ef2-e4b3-4788-ac35-1a6d6b32efa4.png)

Shardingsphere github master code stdout error:
![6BF71168-03E2-4cd4-B156-90F730B6DCCD](https://user-images.githubusercontent.com/20876027/168948576-36c56e2e-7657-4547-843b-d59b366410bd.png)

Does Shardingsphere proxy support Oracle database? If not, is there any plan?

Thanks.

**Comment by strongduanmu** [comment]
@marsgooder ShardingSphere Proxy cannot directly support Oracle database due to the protocol, but we are developing database gateway feature, which can support access to Oracle database through MySQL or PostgreSQL protocol. For more information, you can refer this doc——https://shardingsphere.apache.org/document/current/cn/features/db-gateway/.
