### ISSUE TITLE
Has sharding proxy 5.1.2 been officially released?

### ISSUE THREAD

**Issue by wingkingbobo** [apache/shardingsphere#18382]
## Question
Has sharding proxy 5.1.2 been officially released?
I found the source code of 5.1.2 release on GitHub. I guess this version has been released.
But it was not found on [Apache](https://archive.apache.org/dist/shardingsphere/). The version on docker was earlier than 5.0.0-beta
Where can I get the binary package of 5.1.2. I need it to fix some bugs in the production environment.
Thanks.

**Comment by linghengqian** [comment]
- Because it is still voting in the https://lists.apache.org/thread/f10045vztzq7l5p48glphpxvxnx8sf6p . 

- I don't know how you would define not being on Apache, where the voting process definitely needs to be located on Apache, see https://dist.apache.org/repos/dist/dev/shardingsphere/5.1.2/ . 

- I don't know what you mean by docker not updated, the latest `Dockerfile` has always been located in the `master` branch.

**Comment by wingkingbobo** [comment]
@linghengqian Thank you. It helped me a lot.

**Comment by linghengqian** [comment]
Refer to https://github.com/apache/shardingsphere/releases/tag/5.1.2 , 5.1.2 is already located in Maven Central and Docker Hub.
