### ISSUE TITLE
Why does proxy use hint to force routing to make multiplexing into one request and one thread?

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#18521]
## Question

Why does proxy use hint to force routing to make multiplexing into one request and one thread?

**Comment by strongduanmu** [comment]
Because the Hint feature uses ThreadLocal, it is necessary to ensure that threads in the same connection are reused. For more detailed info, you can refer https://github.com/apache/shardingsphere/blob/eac19a2d497da4ab6074fb101099b151a1cdc7f1/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/HintManager.java.

**Comment by strongduanmu** [comment]
Besides, you can try SQL HINT for some scenario——https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#%E4%BD%BF%E7%94%A8-hint-%E5%88%86%E7%89%87.
