### ISSUE TITLE
Can't config distributed transaction rules when installing by helm chart

### ISSUE THREAD

**Issue by clytzelbj** [apache/shardingsphere#19870]
## Question

Is there any ways to configure distributed transaction rules when I install a proxy cluster by helm chart?

## My trials
I tried to add config to the serverConfig in helm chart according to the official documentation of server.yaml like below.
![image](https://user-images.githubusercontent.com/10139124/182818331-020c076b-91da-4b1c-82f5-0071e5799e3c.png)
But my proxy pods failed to start with the below errors thrown.
![image](https://user-images.githubusercontent.com/10139124/182818913-7dae075a-9a78-4097-82bf-dedbf7559529.png)

## Other Information
Proxy image version: 5.1.3-SNAPSHOT from the master branch on github
Helm version: v3.7.2

**Comment by RaigorJiang** [comment]
As far as I know, helm does not support special YAML tags like `!TRANSTACTION`.
This problem may be resolved in the next version.

**Comment by RaigorJiang** [comment]
@clytzelbj 
In fact, only `mode` and `authority` must be configured in `server.yaml`. Other global rules can be configured by DistSQL , which should solve your problem.

Please refer to [ALTER TRANSACTION RULE ](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/).

Because the default transaction rule type is LOCAL, so there is only ALTER, no CREATE statement.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
