### ISSUE TITLE
How to support the fuzzy query of encrypted fields

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#20435]
Solutions: @strongduanmu 

1. Homomorphism algorithm, but there is no good homomorphic encryption algorithm implemented for now.
2. Besides the cipherColumn and assistedQueryColumn columns, add additional fuzzyColumn and fuzzyAlgorithm which works like  the cipherColumn and assistedQueryColumn columns, rewrite `LIKE plainColumn` into `LIKE fuzzyColumn` to meet user requirements. The `API` changed as below:
```
public final class EncryptColumnRuleConfiguration {
    
    private final String logicColumn;
    
    private final String cipherColumn;
    
    private final String assistedQueryColumn;
    
    private final String plainColumn;
    
    private final String encryptorName;
    
    private final String assistedQueryEncryptorName;
    
    private final Boolean queryWithCipherColumn;

    // new added
    private final String fuzzyQueryColumn;

    // new added
    private final String fuzzyQueryEncryptorName;
 
```

Any other ideas?

Related: #19026

**Comment by strongduanmu** [comment]
This proposal is great, can you explain the implement logic of `fuzzyColumn`, which is very important for the like feature.

**Comment by cheese8** [comment]
> This proposal is great, can you explain the implement logic of `fuzzyColumn`, which is very important for the like feature.

yeah, the `fuzzyColumn` column stores the data processed by the `fuzzyAlgorithm` algorithm. For example:

the original plainColumn value is: `1234567890`
the processed fuzzyColumn may be: `123` or `890` or `12390` which depended on the fuzzyAlgorithm algorithm.

**Comment by freedom-all** [comment]
Good discussion. The current practice here is to use a single password book to enumerate all Chinese and English characters and fill them in the XY axis. When querying, the corresponding value on the XY axis is parsed according to the field, and then the escape query is performed.

**Comment by xinglijun1973** [comment]
@cheese8 if `fuzzyAlgorithm ` is fixed, such as `phone like ‘%<last four digits of mobile phone number>’`， it will do. but what if `company_name like '%sphere%'`? although, I think it  works for some fixed fuzzyAlgorithm.
And another way, I think we can write db function in java, decrpt and do `like`, but I know Oracle and PG support java function, but My sql doesn'nt.

**Comment by xinglijun1973** [comment]
@cheese8 if `fuzzyAlgorithm ` is fixed, such as `phone like ‘%<last four digits of mobile phone number>’`，and `fuzzyColumn` stores last four digits of mobile phone number,  thus it will do. but what if `company_name like '%sphere%'`? although, I think it  works for some fixed fuzzyAlgorithm.
And another way, I think we can write db function in java, decrpt and do `like`, but I know Oracle and PG support java function, and My sql doesn'nt.

**Comment by dajjill** [comment]
The implementation is simple. In the memory, the string that needs to be like matched is fully decomposed according to the length of 1~N, N is the length of the string, and then each decomposed group is encrypted and stored in the memory, so that LIKE can be converted into an equivalent value associated.

**Comment by xinglijun1973** [comment]
I think fuzzy query of encrypted fields should be pushed down to the database for execution. Create a field  `all single word ciphereColomn,` to encrypt the original text in the order of single word (an English alpha or Chinese character). For example, the original text is `sphere,` encrypt the single word `s, p, h, e, r, e` respectively, and put the encrypted results together. When querying, encrypt the parameters in the same way, such as like '%sphere', will rewrite the parameter to '%\<encrypted sphere by single word\>' . Note that such keyword `%,?`   remains unchanged.

**Comment by nanzheng** [comment]
Considering the absolute security of the encryption algorithm, please do not use unverified custom encryption algorithm, please use a secure encryption suite such as (bc), and this encryption feature should be FPE algorithm. rather than homomorphic encryption.

**Comment by charlesvhe** [comment]
After analysis, we draw the following conclusions

**1. Serious encryption algorithms are not available on regular databases**

Serious encryption algorithms such as: Homomorphic Encryption, Searchable Encryption. Both require the database to have the ability to execute related algorithms, which the regular database does not support. You can refer to an experimental implementation based on MySQL https://css.csail.mit.edu/cryptdb/

**2. In order to use the LIKE function of regular database, character by character "encryption" must be used**

Reversible single-character (two-character, few-character) encryption-decryption solution can be cracked by rainbow tables (fixed input corresponds to fixed output, and fixed output corresponds to unique deterministic input). The entire ciphertext can be reversely deduced on the basis of knowing part of the original text and ciphertext. For example, if you know 100 original-ciphertexts, you can reverse all the remaining 10,000 ciphertexts.

**Losted data cannot be retrieved**. Cryptographic hash function can maintain a certain level of security even if the algorithm and secret key are leaked. Weakness: Due to the loss of data, the precision is reduced. Core principle: Multiple different inputs have the same output result, so the inverse result is not fixed.

The single-character digest algorithm can be configured to balance precision and security. The core idea of ​​the algorithm is as follows:
Perform the AND operation on the character ascii code, and lose some binary bits (1 bit is lost, the original result is 1:2; and 2 bits are lost, is 1:4 etc.): For example:
1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ with mask 0b0111_1111_1101, the result is 1014545890a`adedehihilmlmpqpqtutuxyxA@ADEDEHIHILMLMPQPQTUTUXYX

The original SQL like produces 1 record. After losing the precision, it may have 3 records. As the input characters increase, the precision improves, which is the same as the original SQL like semantics.

You can balance precision and security by adjusting the mask.

For Chinese character, if the algorithm and mask are leaked, one output can deduce multiple possible inputs, but excluding rare words, the possible inputs will be greatly reduced, resulting in reduced security. Therefore, we will make a dictionary of common words, no longer mask the unicode code, mask the “index” of the word in the dictionary. Therefore, leaked the algorithm, mask, and dictionary. one output can be reversed multiple common words to improve security, the code as follows:
````

    // ascii 偏移量 防止出现原文
    private int delta = 1;
    // 二进制mask用于丢失精度
    private int mask = 0b1111_1011_1101;
    // 密文起始unicode
    private int start = 0x4e00;
    
    private String dict = "谤杉巫夏辅俯鸵直菱梨滨头矾讯芯巡泥簇何逊谜...";
    
    public static HashMap<Character, Integer> DICT_SEARCH = new HashMap<>(4000);
    
    
    @Override
    public String encrypt(final String plainValue, final EncryptContext encryptContext) {
        if (null == plainValue) {
            return null;
        }
        StringBuilder sb = new StringBuilder(plainValue.length());
        plainValue.chars().forEachOrdered(c -> {
            if ('%' == c) {
                sb.append((char) c);
            } else {
                int masked;
                if (c > 256) {
                    Integer dictCode = DICT_SEARCH.get((char) c);
                    if (dictCode != null) {
                        c = dictCode;
                    }
                    masked = ((c + delta) & mask) + start;
                } else {
                    masked = (c + delta) & mask;
                }
                if ('%' == masked) {
                    sb.append((char) c);
                } else {
                    sb.append((char) masked);
                }
            }
        });
        return sb.toString();
    }

````
For more information, please refer to the attached PDF [隐私数据加密最佳实践.pdf](https://github.com/apache/shardingsphere/files/9683302/default.pdf). We have implemented the above features based on version 5.2.0. My coworker @gxxiong is merging it into the master branch, and will submit the PR later. Welcome to discuss this idea.

**Comment by cheese8** [comment]
> After analysis, we draw the following conclusions
> 
> **1. Serious encryption algorithms are not available on regular databases**
> 
> Serious encryption algorithms such as: Homomorphic Encryption, Searchable Encryption. Both require the database to have the ability to execute related algorithms, which the regular database does not support. You can refer to an experimental implementation based on MySQL https://css.csail.mit.edu/cryptdb/
> 
> **2. In order to use the LIKE function of regular database, character by character "encryption" must be used**
> 
> Reversible single-character (two-character, few-character) encryption-decryption solution can be cracked by rainbow tables (fixed input corresponds to fixed output, and fixed output corresponds to unique deterministic input). The entire ciphertext can be reversely deduced on the basis of knowing part of the original text and ciphertext. For example, if you know 100 original-ciphertexts, you can reverse all the remaining 10,000 ciphertexts.
> 
> **Losted data cannot be retrieved**. Cryptographic hash function can maintain a certain level of security even if the algorithm and secret key are leaked. Weakness: Due to the loss of data, the precision is reduced. Core principle: Multiple different inputs have the same output result, so the inverse result is not fixed.
> 
> The single-character digest algorithm can be configured to balance precision and security. The core idea of ​​the algorithm is as follows: Perform the AND operation on the character ascii code, and lose some binary bits (1 bit is lost, the original result is 1:2; and 2 bits are lost, is 1:4 etc.): For example: 1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ with mask 0b0111_1111_1101, the result is 1014545890a`adedehihilmlmpqpqtutuxyxA@ADEDEHIHILMLMPQPQTUTUXYX
> 
> The original SQL like produces 1 record. After losing the precision, it may have 3 records. As the input characters increase, the precision improves, which is the same as the original SQL like semantics.
> 
> You can balance precision and security by adjusting the mask.
> 
> For Chinese character, if the algorithm and mask are leaked, one output can deduce multiple possible inputs, but excluding rare words, the possible inputs will be greatly reduced, resulting in reduced security. Therefore, we will make a dictionary of common words, no longer mask the unicode code, mask the “index” of the word in the dictionary. Therefore, leaked the algorithm, mask, and dictionary. one output can be reversed multiple common words to improve security, the code as follows:
> 
> ```
> 
>     // ascii 偏移量 防止出现原文
>     private int delta = 1;
>     // 二进制mask用于丢失精度
>     private int mask = 0b1111_1011_1101;
>     // 密文起始unicode
>     private int start = 0x4e00;
>     
>     private String dict = "谤杉巫夏辅俯鸵直菱梨滨头矾讯芯巡泥簇何逊谜...";
>     
>     public static HashMap<Character, Integer> DICT_SEARCH = new HashMap<>(4000);
>     
>     
>     @Override
>     public String encrypt(final String plainValue, final EncryptContext encryptContext) {
>         if (null == plainValue) {
>             return null;
>         }
>         StringBuilder sb = new StringBuilder(plainValue.length());
>         plainValue.chars().forEachOrdered(c -> {
>             if ('%' == c) {
>                 sb.append((char) c);
>             } else {
>                 int masked;
>                 if (c > 256) {
>                     Integer dictCode = DICT_SEARCH.get((char) c);
>                     if (dictCode != null) {
>                         c = dictCode;
>                     }
>                     masked = ((c + delta) & mask) + start;
>                 } else {
>                     masked = (c + delta) & mask;
>                 }
>                 if ('%' == masked) {
>                     sb.append((char) c);
>                 } else {
>                     sb.append((char) masked);
>                 }
>             }
>         });
>         return sb.toString();
>     }
> ```
> 
> For more information, please refer to the attached PDF [隐私数据加密最佳实践.pdf](https://github.com/apache/shardingsphere/files/9683302/default.pdf). We have implemented the above features based on version 5.2.0. My coworker @gxxiong is merging it into the master branch, and will submit the PR later. Welcome to discuss this idea.

Thanks for your comments,  and I think it's a implementable idea/solution for the `LIKE`, and we are almost matched.

I think what I should say is: 
In terms of decoupling, we could have 4 columns for the logicColumn at most: the plainColumn, the cipherColumn, the assistedQueryColumn and the fuzzyQueryColumn,   the cipherText at cipherColumn is for decryption purposes, the assistedQueryText at assistedQueryColumn is for `=` query, so the fuzzyQueryText at fuzzyQueryColumn is for `LIKE` query only. So, I think even if the fuzzy query algorithm which is specified by fuzzyQueryEncryptorName is very simple or not very safe, as long as it could desensitize the original plaintext, it's ok.

Welcome to submit the PR, and I think there are below sub tasks:

- [ ] add the fuzzyQueryColumn and fuzzyQueryEncryptorName
- [ ] rewrite the sql while `LIKE` operator contained and UT, SIT
- [ ] refactor the visit logic for distsql and UT, SIT
- [ ] support the fuzzyQueryColumn and fuzzyQueryEncryptorName for distsql and UT, SIT
- [ ] provider fuzzy query algorithms at least 1

**Comment by gxxiong** [comment]
Design Reference assistedQueryColumn, just rewrite LIKE plainColumn into LIKE fuzzyColumn.I will split the pr into several parts to submit.

**Comment by strongduanmu** [comment]
@gxxiong That's great, I have assign this issue to you.

**Comment by strongduanmu** [comment]
All task has been finished, so I will close this issue.
