### ISSUE TITLE
Configuring the database of oracle

### ISSUE THREAD

**Issue by 13145512239** [apache/shardingsphere#20635]
jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.0.12)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.0.22)(PORT = 1521))(LOAD_BALANCE = yes)(FAILOVER = ON)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = rac)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 20)(DELAY = 15))))

shardingsphere 5.0.0 can pass this url, but 5.1.2 can not ,i think this is a bug, can you fix this ?

**Comment by strongduanmu** [comment]
Thank you for your feedback, we will investigate this problem.

**Comment by 13145512239** [comment]
ok, what are you going to do about it ? Is it in version 5.1.2 or next version ?

**Comment by 13145512239** [comment]
ok, what are you going to do about it ? Is it in version 5.1.2 or next version ?

**Comment by 13145512239** [comment]
> 

ok, what are you going to do about it ? Is it in version 5.1.2 or next version ?

**Comment by terrymanu** [comment]
Hello, it's inevitable that there will be compatibility issues with the various versions of ShardingSphere. Due to the vast number of combinations, it's impossible to address each one individually. To better face the future, the community would like to focus on resolving issues with the current version. For issues related to upgrades, please read the documentation for the respective version. If you encounter a bug in the new version (not a configuration issue), please submit a separate issue.
