### ISSUE TITLE
DataSourcePropertiesValidator should catch SQLException and ShardingSphereInternalException only

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#20815]
Catch exception is not recommended, please investigate the class  DataSourcePropertiesValidator, and try to instead of catch exception to SQLException and ShardingSphereInternalException.

Just search `// TODO check why catch exception here, can it simplify to catch SQLException and ShardingSphereInternalException?` to find the codes.

**Comment by tianhao960** [comment]
hi, @terrymanu , I'd like to try this.

**Comment by strongduanmu** [comment]
> hi, @terrymanu , I'd like to try this.

@tianhao960 Assigned. Could we finish this issue in 5.2.1?

**Comment by tianhao960** [comment]
> > hi, @terrymanu , I'd like to try this.
> 
> @tianhao960 Assigned. Could we finish this issue in 5.2.1?

hi, I am afraid I need some time to finish this and  before 5.2.2 release, it could be done. thanks.

**Comment by tianhao960** [comment]
it seems that
 `DataSourcePoolCreator.create(dataSourceProps);`
will throw Exception which caused by `@SneakyThrows(ReflectiveOperationException.class)` at class DataSourcePoolCreator and ShardingSphereServiceLoader.

and DataSourcePropertiesValidator can not catch checked exception ReflectiveOperationException.

**Comment by TeslaCN** [comment]
Hi @tianhao960 
Is there any progress?

**Comment by sandynz** [comment]
It's already fixed by #22217
