### ISSUE TITLE
about timezone has no effect

### ISSUE THREAD

**Issue by Spackys** [apache/shardingsphere#21416]
When I use a jdbc-url with serverTimezone=Asia/Shanghai or serverTimezone=GMT%2B8, There is no effect. When insert date to mysql database is still UTC timezone, also mysql timezone is set to '+08:00'. For example, now is 14:13, use code the date is correct, but database date is 6:13.Directly use other tools connect database is normal with this jdbc-url setting.How can I set to correct the timezone? Thanks!

**Comment by RaigorJiang** [comment]
The following information cannot be obtained from the issue description:
- Are you using ShardingSphere-JDBC or ShardingSphere-Proxy?
- What version are you using?

Please follow the issue template to submit information in order to get help, thank you.

---
Considering this issue has been around for a long time, I'm closing it now. If you still have the same problem, please reopen it or submit a new one

**Comment by byteboycn** [comment]
I have same problem with using ShardingSphere-Proxy v5.3.1

**Comment by RaigorJiang** [comment]
@byteboycn 
When using ShardingSphere-Proxy, both the url that the client connects to the Proxy and the url that the Proxy connects to dataSources need to set parameters, please try it.
