### ISSUE TITLE
Can shardingsphere integrated base transactions be optimized to support seata cross-process invocation transactions?

### ISSUE THREAD

**Issue by githust66** [apache/shardingsphere#21947]
Can shardingsphere integrated base transactions be optimized to support seata cross-process invocation transactions? The implementation of the introduction of shardingsphere base transaction dependencies not only supports the existing functionality but also allows the user to choose whether to enable the transaction feature of seata across service invocations.

**Comment by TeslaCN** [comment]
Hi @FlyingZC 
Please help check this.

**Comment by FlyingZC** [comment]
No plan for now.Now ShardingSphere supports internal BASE transaction, but not supported begin BASE transaction from outside of ShardingSphere,because when started a BASE transaction from outside of ShardingSphere, Shardingsphere does not know that it needs to open transactions to ensure the consistency between the physical tables corresponding to the logical tables,this requires cooperation between Seata and ShardingSphere.

**Comment by RaigorJiang** [comment]
Without this plan, I will close this issue.
