### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid binding table configuration in ShardingRuleConfiguration

### ISSUE THREAD

**Issue by LiYuanHaooo** [apache/shardingsphere#22001]
sharding-proxy 5.2.0

config-sharding.yaml
```shell
rules:
- !SHARDING
  tables:
   ...

  bindingTables:
    - tmdb_trademark,tmdb_goods
    - tmdb_trademark,tmdb_trademark_owner,tmdb_owner
```

exception when starting sharding-proxy
![image](https://user-images.githubusercontent.com/26320670/200468764-b31f45b0-5dce-4157-8d66-7e042151d3db.png)

**Comment by sandynz** [comment]
Hi @LiYuanHaooo , I had a look at `ShardingRule.isValidBindingTableConfiguration`, if it return `false`, then `Invalid binding table configuration in ShardingRuleConfiguration` will be thrown.
There're much cases will cause `false` returning.

Since the `config-sharding.yaml` is not completed, could you debug to check what's wrong in the configuration?
