### ISSUE TITLE
 JPA auto create table throws an exception

### ISSUE THREAD

**Issue by Wendymayu** [apache/shardingsphere#22876]
## Question

when I use sharding-jdbc in  project and datasource has table T_MSSI_KMS_SECRET_KEY, JPA auto create table throws an exception as belows, have you seen this problem?

Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate Session#******#ption is org.apache.shardingsphere.sharding.route.engine.exception.TableExistsException: Table 'T_MSSI_KMS_SECRET_KEY' already exists.

here is my JPA setting:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

here is my shardingsphere setting by javaBean
    private static ShardingTableRuleConfiguration getTMssiKmsSecretKeyTableRuleConfiguration() {
        ShardingTableRuleConfiguration result = new ShardingTableRuleConfiguration(
                "T_MSSI_KMS_SECRET_KEY", "db1.T_MSSI_KMS_SECRET_KEY");
        return result;
    }

**Comment by azexcy** [comment]
Hi @dandanwendy it is impossible to know exactly why the problem occurred from the description.
What database are you using?

**Comment by dandanwendy** [comment]
> Hi @dandanwendy it is impossible to know exactly why the problem occurred from the description. What database are you using?

mysql 8.0, and driver is driver-class-name: org.mariadb.jdbc.Driver. I can't show more infomation cause company's infomation security.

**Comment by dandanwendy** [comment]
> Hi @dandanwendy it is impossible to know exactly why the problem occurred from the description. What database are you using?

when I set ddl-auto none rather than update, there is no exception.
  jpa:
    hibernate:
      ddl-auto: update

**Comment by azexcy** [comment]
> > Hi @dandanwendy it is impossible to know exactly why the problem occurred from the description. What database are you using?
> 
> when I set ddl-auto none rather than update, there is no exception. jpa: hibernate: ddl-auto: update

Ok, I guess maybe this table really exists already, you could add log `org.apache.shardingsphere.infra.executor.sql.log.SQLLogger` which will output Actual SQL, then we know exactly which statements were executed

**Comment by wanghongzhou** [comment]
I also encountered the same issue, so I debugged the code. I found that in the `performTablesMigration` method of the `GroupedSchemaMigratorImpl` class, when calling `final NameSpaceTablesInformation tables = existingDatabase.getTablesInformation(namespace);` it failed to retrieve the tables. so resulted in the creation of new tables.

Upon further investigation, I noticed that the `currentCatalog` field in the `JdbcEnvironmentImpl` was empty. This caused the `AbstractInformationExtractorImpl` to be unable to retrieve table information when calling `getTable`. The root cause of the issue appears to be that the `ShardingSphereConnection` class's `getCatalog` method is returning null. 

I'm using Hibernate version 6.2.5 and ShardingSphere version 5.3.2.

**Comment by terrymanu** [comment]
The issue involves many thrid-party dependencies, but we are focusing only on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, could you please debug the program to show the specific issue with the JDBC calls, or provide a demo on GitHub for easy reproduction of the problem?
