### ISSUE TITLE
How to implement customized encrypt algorithm in 5.3.0

### ISSUE THREAD

**Issue by tianshuainan** [apache/shardingsphere#22907]
Currently, shardingsphere version is 4.1.1 in my project,so I want to update to 5.3.0.  i am using shardingsphere-jdbc's customized encryption feature.now,I cannot find related docment and conf.  Can you provide some example or docment? Thanks a lot!

**Comment by tianshuainan** [comment]
In class EncryptAlgorithm, there is no override method such as previous "`encrypt(Object o) ,decrypt(String ciphere)`"
`public class MyEncryptor implements EncryptAlgorithm {}`

**Comment by strongduanmu** [comment]
Hi @tianshuainan, you can try to implement StandardEncryptAlgorithm interface. Since we have added support for like, currently EncryptAlgorithm has two sub-interfaces StandardEncryptAlgorithm and LikeEncryptAlgorithm, which are used for standard encryption algorithms and LIKE encryption algorithms respectively.

**Comment by tianshuainan** [comment]
nb! Thanks you a lot!  Your answer is very helpful to me! 
I stiill have a question: Is queryAssistedEncryptor is disappear or replaced by other? beacuse i want to query by encryptedfield.
