### ISSUE TITLE
shardingProxy v5.2.1 insert successfully but cannot return the PK primary

### ISSUE THREAD

**Issue by lanxw** [apache/shardingsphere#23047]
When shardingProxy5.2.1 integrates mybatis-plus v3.5.2, calling the insert method successfully, but cannot return the PK primary key value when entity have associated(Use Single Insert is OK),I using the default snowflake algorithm and build in spring boot v2.7.6 and mysql 8
Test Case in shardingJDBC5.2.1 is OK，can return the PK primary 
Help, Thanks!
```java
@TableName("bus_statement")
@Data
public class Statement {
    @TableId(type = IdType.ASSIGN_ID)
    private Long statementNo;
    ......
}
---------------------------------------------------
@Test
public void testInsertAssociatedData(){
        Statement statement = new Statement();
        ......
        statementMapper.insert(statement);
        for (int j = 0; j <3 ; j++) {
            StatementItem item = new StatementItem();
            //statement.getStatementNo() is NULL
            item.setStatementNo(statement.getStatementNo());
            ......
            statementItemMapper.insert(item);
        }
}
---------------------------------------------------
rules:
- !SHARDING
  tables:
    bus_statement:
      actualDataNodes: customer_data$->{0..1}.bus_statement$->{0..1}
      databaseStrategy:
        standard:
          shardingColumn: customer_phone
          shardingAlgorithmName: alg_inline
      tableStrategy: 
        standard:
          shardingColumn: statement_no
          shardingAlgorithmName: alg_mod
      keyGenerateStrategy:
        column: statement_no
        keyGeneratorName: alg_snowflake
  keyGenerators:
    alg_snowflake:
      type: SNOWFLAKE
  shardingAlgorithms:
    alg_mod:
      type: MOD
      props:
        sharding-count: 2
    alg_inline:
      type: INLINE
      props:
        algorithm-expression: customer_data$->{customer_phone % 2}

**Comment by strongduanmu** [comment]
@lanxw Thank you for your feedback, I will check this problem soon.

**Comment by jeff-lai** [comment]
I encountered the same issue.

**Comment by strongduanmu** [comment]
Hi @lanxw @jeff-lai, I did some research on this issue. In MySQL, we use `auto_increment` to identify the primary key that needs to be auto-incremented. When we execute the insert statement, MySQL will return lastInsertId and updateCount, and the MySQL driver will calculate the auto-increment id value based on updateCount and autoIncrementValue.

Therefore, we cannot support Proxy to obtain auto-increment ids when using the SNOWFLAKE algorithm, because the SNOWFLAKE algorithm is not continuous.

In order to support the MySQL auto-increment id feature, I added isSupportAutoIncrement to KeyGenerateAlgorithm. We can implement our own auto-increment id algorithm based on the SPI interface, and then override isSupportAutoIncrement and return true. At this time, we can support returning auto-increment id.
