### ISSUE TITLE
PostgreSQLStatementSQLVisitor visitExprList StackOverflowError

### ISSUE THREAD

**Issue by zeyuwang01** [apache/shardingsphere#25480]
## Bug Report
**Which version of ShardingSphere did you use?**
shardingsphere-sql-parser-postgresql-5.1.1-sources.jar

**use case**
```java
AbcExample abcExample = new AbcExample();
AbcExample.Criteria abcExampleCriteria = AbcExample.createCriteria();
abcExampleCriteria.andCustomerIdIn(collect.stream().collect(Collectors.toList()));
List<Abc> list = AbcMapper.selectByExample(abcExample);
```

**error log**
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/109566148/236594456-380aa333-bbeb-40b0-8598-c9b561d20439.png">

**Comment by FlyingZC** [comment]
@zeyuwang01 Hi, please provide the SQL.

**Comment by xghsunshine** [comment]
> @zeyuwang01 Hi, please provide the SQL.

This seems like it could be SQLVisitorEngine visit a deep ParseTree, 
like be "select * from xxx where id in (xxxx,xxx,xxx,xx.....)". because use recursive method

**Comment by ldong1204** [comment]
the same probleam I am, but “a in (1,2,3,4,5...50000) “ is ok ，Howerver " (( a= 1 and b=2 )  or (a = 3 and b= 4) or ..... 1000)" is not ，and I don't how to deal with this problem without increaming -Xss.If I use the subSelect after"in" it will be not allowed by shardingPhere. So that is a dead cycle?

**Comment by Keanhua** [comment]
i found the same problem，can someone fix it？
