### ISSUE TITLE
Sharding does not support configuring ActualDataNodes to ${01.. 02}. If I want to split the table by month, regardless of year, how should I configure it

### ISSUE THREAD

**Issue by ThisOnly** [apache/shardingsphere#26111]
## Bug Report
Configure the table according to the following diagram, but it cannot be successful. Why is it

![image](https://github.com/apache/shardingsphere/assets/41990755/63c1ce6e-9b81-4c5e-8739-6a9ab37d47d9)

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
The above configuration can be executed correctly

### Actual behavior
error

**Comment by linghengqian** [comment]
- In fact you can use Groovy Shell to verify, I think you want to use `0${1.. 2}` instead of `${01.. 02}`.  

- For the second question, there is actually no need to consider Groovy syntax. You can directly dynamically modify the `actualDataNodes` through `DistSQL`, or take out the `ContextManager` and modify it manually.  

- I think you can wait for #22899 to be closed, I have a batch of unmerged PRs working on this issue.  Once #22899 is closed, the configuration of this expression can be customized via SPI.

**Comment by linghengqian** [comment]
- The new SPI was introduced in the related PR at https://github.com/apache/shardingsphere/issues/22899 , this issue can now define `List<String>` via an new Row Value Expression SPI implementation.

**Comment by KeZhimin** [comment]
ds_0.t_user_$->{2023..2050}$->{(1..12).collect{t ->t.toString().padLeft(2,'0')}}
