### ISSUE TITLE
High Number of Established TCP Connections with ShardingSphere-Proxy 5.3.1

### ISSUE THREAD

**Issue by mytudan** [apache/shardingsphere#26445]
I am encountering an issue with ShardingSphere-Proxy version 5.3.1. When my application establishes a database connection with the proxy, I have noticed that a large number of TCP connections between the proxy and the application remain in the 'ESTABLISHED' state. Moreover, the number of these connections continues to increase daily without any reduction.

However, when I check from the application side, the number of connections seems normal, only a few, which is quite odd. Shouldn't the TCP connections with the proxy also be terminated when the application disconnects?

I would appreciate any assistance you can provide regarding this matter.

Thank you.

**Comment by mytudan2022** [comment]
I have discovered that Apache Kafka had an issue similar to the one I'm encountering, where the open file descriptor count approaches the limit due to terminated client instances. Kafka has resolved this problem in subsequent versions. The related link to the issue in Kafka can be found here: [KAFKA-2096](https://issues.apache.org/jira/browse/KAFKA-2096).

My question is: Does ShardingSphere have a similar configuration for keepalive like Kafka? This configuration appears to be an effective solution to the problem, and I'm interested in knowing if a similar option exists within ShardingSphere.

Thank you for your assistance.

**Comment by terrymanu** [comment]
First, we need to determine how this issue occurred and how to reproduce it, and then we can consider how to resolve it. What actions can be taken to reproduce this state?
