### ISSUE TITLE
How to add custom WallConfig, Filter in the Spring Boot ?

### ISSUE THREAD

**Issue by gufeng710** [apache/shardingsphere#26868]
### Environment
springboot 2.1.3.RELEASE
sharding-jdbc-spring-boot-starter:4.1.1
druid 1.1.11

### How
I want to configure druid custom filter property in yml。But I find org.apache.shardingsphere.spring.boot.util.DataSourceUtil never call com.alibaba.druid.pool.DruidAbstractDataSource#setProxyFilters。
Is it true that yml does not support configuration？
Can I only use the JavaConfig way to set it up DruidDataSource？？

**Comment by linghengqian** [comment]
- It looks like https://github.com/apache/shardingsphere/issues/21211#issuecomment-1932123528 is behaving normally and the fix is already on the master branch.
- `org.apache.shardingsphere.spring.boot.util.DataSourceUtil` has been removed, please use shardingsphere 5.4.2-SNAPSHOT to provide unit tests.

**Comment by linghengqian** [comment]
- Due to lack of reproducible unit tests, I'm closing this issue.
