### ISSUE TITLE
navicat view can't be update real time

### ISSUE THREAD

**Issue by fanchuanlin** [apache/shardingsphere#27912]
hi all，i have a requestion。
my shardingsphere-proxy version is 5.1.2, and i shardingsphere-proxy's mode is cluster ,it has two nodes.
when i commit a alter sql eg:
```
alter table  `U_SITE_WITHDRAWALS`
add column `create_time` datetime NOT NULL COMMENT '提现时间'；
```
then the real db(mysql) was commited,but the navicat table view  can't be updated real time.

but sql can use the new column.
`
SELECT create_time FROM `U_SITE_WITHDRAWALS` ORDER BY create_time desc limit 1;
`
what can i do or Config for navicat view  be update real time？

**Comment by azexcy** [comment]
@fanchuanlin What I know, support navicat is not yet perfect, so there are some strange problem with using it.

**Comment by fanchuanlin** [comment]
The problem was disappeared when i restarted shardingsphere-proxy.i don't know the reason.but i think maybe the shardingsphere-proxy cache refreshed real time??

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
