### ISSUE TITLE
Jetcd will drop java 8

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/shardingsphere#28376]
Hi shardingsphere community, just for note that Jetcd will drop java 8, please check https://github.com/etcd-io/jetcd/issues/1218

**Comment by linghengqian** [comment]
- ShardingSphere's mailing list discussed the matter earlier this year, but it's clearly not possible for the project to raise the minimum JDK **runtime** version at this stage. Although ShardingSphere now requires JDK11+ to **compile**. Reference https://lists.apache.org/thread/kgtfx5vnw73o61lkvdshyfvjfvvzk3js .

- I personally don’t think changes made to Jetcd will affect ShardingSphere, because on the ShardingSphere side, the processing logic for metadata preservation related to Jetcd is introduced through SPI. If breaking changes occur in the future, users can implement SPI themselves for new versions of Jetcd.

**Comment by liangyuanpeng** [comment]
Thanks for your confirm that!
