### ISSUE TITLE
Is there any change with the configuration of shardingsphere-proxy of different version?

### ISSUE THREAD

**Issue by Cindyxin228** [apache/shardingsphere#28413]
After searching the Internet, I learn that since v5.0.0, the sharding rule has only standard、complex、hint  and none (no inline). And when I learn the code, I find in the "algorithm" folder of sharding, there's several folders (sections) including datetime, mod, hint, range and so on. And I can't find concrete explanation of configuration related to v5.4.0 and I'm confused when configuring. 
So could you tell me where to find the concrete explanation of configuration related to v5.4.0 or tell me the configuration of v5.4.0 is the same as which version? (still only four types —— standard、complex、hint  and none ?)
Thanks very much.

**Comment by terrymanu** [comment]
Hello, it's inevitable that there will be compatibility issues with the various versions of ShardingSphere. Due to the vast number of combinations, it's impossible to address each one individually. To better face the future, the community would like to focus on resolving issues with the current version. For issues related to upgrades, please read the documentation for the respective version. If you encounter a bug in the new version (not a configuration issue), please submit a separate issue.
