### ISSUE TITLE
Add more unit tests for EncryptColumnExistedReviser

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28548]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for EncryptColumnExistedReviser to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by VaishnaviMudaliar** [comment]
Hey 👋 I am interested in working on this issue, can it be assigned to me?

**Comment by tuichenchuxin** [comment]
> Hey 👋 I am interested in working on this issue, can it be assigned to me?

this issue has been assigned, please have another one.

**Comment by Sakshi-75** [comment]
Hi @tuichenchuxin , I had a query regarding the behavior of the isExisted method in the EncryptColumnExistedReviser.class .
If I pass a column name that doesn't exist in the encryptTable then according to the logic:
encryptTable.isCipherColumn(originalName) will be False
encryptTable.isAssistedQueryColumn(originalName) will be False
encryptTable.isLikeQueryColumn(originalName) will be False
But according to the code it'll be: False || !False && !False => False || True && True => True
I just wanted to confirm if that's expected behavior for this code.

**Comment by tuichenchuxin** [comment]
@Sakshi-75 
Yes, your logic is correct.
