### ISSUE TITLE
Transactions are not rolleback!!!

### ISSUE THREAD

**Issue by doveylovey** [apache/shardingsphere#28547]
### Which version of ShardingSphere did you use?
v5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Transaction rollback

### Actual behavior
Transactions are not rolleback

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
config：
![image](https://github.com/apache/shardingsphere/assets/28882195/c41982ab-20ba-4396-b083-c011f67a755e)

### Example codes for reproduce this issue (such as a github link).
key code:
![image](https://github.com/apache/shardingsphere/assets/28882195/699356fe-9a0f-4853-bcae-f60858eded8a)
![image](https://github.com/apache/shardingsphere/assets/28882195/142cbf37-280e-4023-86ca-e9f9d0645030)
![image](https://github.com/apache/shardingsphere/assets/28882195/e7855f56-ad87-41cf-9b5b-d7c765cde382)

Why is there data in the database: 
![image](https://github.com/apache/shardingsphere/assets/28882195/413cdcbd-d8f6-4f69-9cfb-1d002120ba72)

What should I do to ensure that the program works correctly???

**Comment by terrymanu** [comment]
Hello, it's inevitable that there will be compatibility issues with the various versions of ShardingSphere. Due to the vast number of combinations, it's impossible to address each one individually. To better face the future, the community would like to focus on resolving issues with the current version. For issues related to upgrades, please read the documentation for the respective version. If you encounter a bug in the new version (not a configuration issue), please submit a separate issue.
