### ISSUE TITLE
The rewrite method will remove the schema from SQL, resulting in SQL execution errors

### ISSUE THREAD

**Issue by study-renjie** [apache/shardingsphere#28601]
## The rewrite method will remove the schema from SQL, resulting in SQL execution errors
sql如下
![image](https://github.com/apache/shardingsphere/assets/43563096/4cf73d68-bf15-433d-bfeb-a31d3d706af1)
报错如下
`{
    "message": "\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'servicedb.partitions' doesn't exist\r\n### The error may exist in file [D:\\Project\\SpringBootDemo\\target\\classes\\mapper\\TestDao.xml]\r\n### The error may involve defaultParameterMap\r\n### The error occurred while setting parameters\r\n### SQL: SELECT partition_name partitionName, partition_description partitionDesc, table_rows rowCount         FROM INFORMATION_SCHEMA.PARTITIONS         WHERE TABLE_SCHEMA = SCHEMA ()           AND TABLE_NAME ='t_operationlog'           AND partition_name = ?\r\n### Cause: java.sql.SQLSyntaxErrorException: Table 'servicedb.partitions' doesn't exist\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'servicedb.partitions' doesn't exist"
}`

**Comment by terrymanu** [comment]
Hello, it's inevitable that there will be compatibility issues with the various versions of ShardingSphere. Due to the vast number of combinations, it's impossible to address each one individually. To better face the future, the community would like to focus on resolving issues with the current version. For issues related to upgrades, please read the documentation for the respective version. If you encounter a bug in the new version (not a configuration issue), please submit a separate issue.

**Comment by liuzhenghua** [comment]
你是怎么复现这个问题的，我用5.5.0日志中也不规律出现这个错误。但是我直接用dbeaver这种客户端工具连接shardingsphere-proxy执行：
SELECT * from information_schema.partitions; （成功）
SELECT * from partitions;（报错，但是不会有那个错误日志）

现在怀疑是不是sharding-jdbc连接后执行这个sql会有这个问题？
