### ISSUE TITLE
Does shardingsphere support clickhosue?

### ISSUE THREAD

**Issue by niushaoda** [apache/shardingsphere#28892]
Does shardingsphere support clickhosue?

**Comment by niushaoda** [comment]
Caused by: java.lang.UnsupportedOperationException: Unsupported database from url: 'jdbc:clickhouse:http://11.141.221.12:8123/weflow_test_1?druid.stat.slowSqlMillis=5000&druid.stat.mergeSql=true'

**Comment by niushaoda** [comment]
Caused by: java.lang.UnsupportedOperationException: Unsupported database from url: 'jdbc:clickhouse:

**Comment by linghengqian** [comment]
- Can you create a git containing minimal reproducible unit tests using testcontainers including clickhouse?  The unit tests never tested clickhouse, but the related testcontainers url.

**Comment by Afsalmc** [comment]
Same experience with Vertica DB. If It has a jdbc driver the support should be there cause shardingsphere jdbc supports jdbc standard right?

**Comment by linghengqian** [comment]
> Same experience with Vertica DB. If It has a jdbc driver the support should be there cause shardingsphere jdbc supports jdbc standard right?

- That's right, as long as a JDBC driver exists, the corresponding data source can be included in ShardingSphere's metadata.

- @Afsalmc  Can you provide a git containing unit tests using testcontainers? I need to know exactly what class is causing this type of problem.

**Comment by linghengqian** [comment]
- While investigating the usability of testcontainers under GraalVM Native Image, I noticed design issues with certain PRs for some related classes. I've opened #29291 . 

- The current issue still lacks example git to assist in reproduction.

**Comment by linghengqian** [comment]
- @Afsalmc I added the description of databases without community LICENSE such as Vertica DB via javadoc in #29297. In general, you need to implement the Vertica DB dialect yourself, and before implementing it you can manually port it to a known SQL dialect implementation, such as MySQL or SQL92.
- @niushaoda Clickhouse is now parsed through the MySQL dialect, but in order to get rid of the MySQL dialect, the relevant sub-modules of clickhouse need to do more SPI implementation, which requires someone to know the specific content of the Clickhouse dialect.
