### ISSUE TITLE
ShardingSphereDataSource to be used in conjunction with MyBatisPlus

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#28926]
As described in the official documentation：
configure ShardingSphereDataSource to be used in conjunction with ORM frameworks such as JPA, Hibernate, and MyBatis.

Please give me an example for  used in conjunction with MyBatisPlus

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer entertain such issues. Please read the documentation or provide more effective information when submitting an issue.
