### ISSUE TITLE
when I use NarayanaConfigurationFileGenerator,if the transaction takes too long time,will throw Exception

### ISSUE THREAD

**Issue by q991103914** [apache/shardingsphere#29037]
there is the Exception.
![1699973267858](https://github.com/apache/shardingsphere/assets/45675995/76d263d1-3359-4c67-9a7f-280312cd11e6).
I guess because The NarayanaConfigurationFileGenerator overwrite my own configuration.There is my configuration,
![image](https://github.com/apache/shardingsphere/assets/45675995/90ffa172-2f2e-47d8-ba39-62cac74b2988)
I found the CoordinatorEnvironmentBean.defaultTimeout  is always overwrited by system when I run the project.What can I do
to fix the bug.

**Comment by linghengqian** [comment]
- I documented this phenomenon in #30132 and #30102 , which requires you to manually call the Narayana Java API in the **bootstrap class** of your own project.
- After calling the Narayana Java API, `jbossts-properties.xml` can be deleted. Because the content of `jbossts-properties.xml` will always be updated by Narayana, this is not something that can be controlled on the ShardingSphere side.
- It looks like the following. Obviously if you do not use `jbossts-properties.xml`, you also need to provide `CoreEnvironmentBean.nodeIdentifier`.

```java
import com.arjuna.ats.arjuna.common.CoreEnvironmentBeanException;
import com.arjuna.ats.arjuna.common.arjPropertyManager;

public class ExampleUtils {
    public void initNarayanaInstance() {
        try {
            arjPropertyManager.getCoreEnvironmentBean().setNodeIdentifier("1");
            arjPropertyManager.getCoordinatorEnvironmentBean().setDefaultTimeout(2000);
        } catch (CoreEnvironmentBeanException e) {
            throw new RuntimeException(e);
        }
    }
}
```
- This is the approach from the ShardingSphere JDBC side. For ShardingSphere Proxy, you may have to consider multiple Narayana instances. But in any case, this has nothing to do with the ShardingSphere side. This is actually a documentation issue on the Narayana side.

**Comment by linghengqian** [comment]
- Oh, I understood it wrong, `NarayanaConfigurationFileGenerator` is on ShardingSphere side. It seems like there is a lack of additional way to handle it, do you have any idea?

**Comment by linghengqian** [comment]
- There is a problem involved here. `NarayanaConfigurationFileGenerator` has long been deleted. Are you sure this is a problem that exists in the master branch?

**Comment by linghengqian** [comment]
- Closed due to no response.
