### ISSUE TITLE
some question about Readwrite-splitting

### ISSUE THREAD

**Issue by sui6666666** [apache/shardingsphere#30862]
![微信图片_20240412175010](https://github.com/apache/shardingsphere/assets/37390575/8b958a34-64e0-4e99-8207-6959503b9edf)

Regarding the following sentence described in the figure, "the master database is responsible for processing transactional addition, deletion and modification operations, and the slave database is responsible for processing query operations, which can effectively avoid row locks caused by data updates, so that the query performance of the whole system has been greatly improved."

I have a question, when the insert update delete of the master database is synchronized to the slave database, is there no lock on the data from the slave database?

关于图中的描述的下面这句话，“主库负责处理事务性的增删改操作，从库负责处理查询操作，能够有效的避免由数据更新导致的行锁，使得整个系统的查询性能得到极大的改善”

我有个疑问，当主库的insert update delete  同步给从库的时候，难道从库这些数据就不产生锁了吗？怎么能有效避免由数据更新导致的行锁那？

**Comment by TherChenYang** [comment]
- Read-write separation can only reduce the pressure on the master database. Taking MySQL as an example, when there are a large number of DML and DDL flowing to the slave database, there will be a problem of master-slave delay because the master database can execute concurrently while the Slave SQL Running thread in older versions cannot. If a DDL needs 10 seconds to execute, all other DDL statements have to wait for this one to finish executing before they can continue executing on the slave database. In newer versions of MySQL, the Slave SQL Running thread has been adjusted to allow multiple threads to simultaneously execute SQL from the master database's binlog.

- The application scenario of read-write separation is that the reading of data is much larger than the writing of data. If a single-node database is used at this time, the database will be under great pressure at this time. Therefore, the read-write separation strategy is adopted at this time. Since the data The write rate is not very large, using read-write separation at this time can solve the problem well while avoiding master-slave delay
