### ISSUE TITLE
jpa insert json field causes parameters to be lost

### ISSUE THREAD

**Issue by penweizgx** [apache/shardingsphere#31945]
JPA (hibernate6.4) is used in the project for data access, one of which is a json object field. Now when insert is executed, there will be one less parameter. What is the reason?

raw sql
```
 insert into t_org_school (city,county,detail,province,info,id) values (?,?,?,?,cast(? as json),?)
```
shardingjbdc sql 
```
insert into t_org_school_101 (city,county,detail,province,info,id) values (?, ?, ?, ?, cast(? as json), ?) ::: [333, 333, xxxxxx, 222, {"address":null,"logo":null,0}]
```
In the above sql, the id parameter of the last field is lost.

**Comment by terrymanu** [comment]
The information you provided does not fully understand the issue. Please refer to the issue template to fill the necessary information, which will help us catch the problem clearly.

**Comment by gplayer2** [comment]
![Snipaste_2024-09-05_20-20-16](https://github.com/user-attachments/assets/b434cfbd-de19-4044-b6a8-91286b99c7bf)

The issue is as follows: as shown in the screenshot, when parsing cast(? as json), the outer layer is a FunctionSegment. After recursive calls, a DataTypeSegment is obtained, but this method does not parse DataTypeSegment, leading to it not being added to the segments variable, resulting in one missing parameter.
