### ISSUE TITLE
shardingjdbc 5.1.2 pagination routed to different db

### ISSUE THREAD

**Issue by huangconghe** [apache/shardingsphere#32366]
shardingjdbc 5.1.2+mybatisplus+sqlserver
pagination by mybatisplus,  query data sql Should be routed to db1,select count(1) routed to db1 ,but with selectdata as() routed to db0

ShardingSphere-SQL - Actual SQL: ds1 ::: SELECT COUNT(1) AS TOTAL FROM 
[http-nio-6001-exec-3] INFO  ShardingSphere-SQL - Actual SQL: ds0 ::: WITH selectTemp AS (SELECT TOP 100 PERCENT  ROW_NUMBER() OVER (ORDER BY CURRENT_TIMESTAMP) as __row_number__, 
it routed to different db

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
