### ISSUE TITLE
mybatisplus+sqlserver route to default db

### ISSUE THREAD

**Issue by huangconghe** [apache/shardingsphere#32383]
## Question
sqlparse
shardingjdbc5.1.2+mybatisplus+sqlserver route to default db
Actual SQL: ds0 :: WITH selectTemp AS (SELECT TOP 100 PERCENT
ROW_ NUMBER OVER (order by tmp.id) as_ row number, tmp.id from (
select tb.id
from a
left join bm
on tb.item id =
m.item id
WHERE tb.is deleted = 'O'
) tmp
order by tmp.item id) SELECT * FROM selectTemp WHERE
row number_ BETWEEN,1 AND 20 ORDER BY _row number...
WITH selectTemp AS ... SELECT * FROM selectTemp WHERE Not execute the custom dbrules,
before this, select count(1).. is correct

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
