### ISSUE TITLE
slow sql

### ISSUE THREAD

**Issue by 13145512239** [apache/shardingsphere#32399]
## Question

Hi，I use shard 5.2.0，and i find a question，when i first query database，oracle or mysql，it will spend more time，how do i fix this?

**Comment by linghengqian** [comment]
I would say this is essentially caused by shardingsphere querying the database metadata. If you are using spring boot, you can set up a spring bean of `org.springframework.boot.ApplicationRunner`, which uses shardingsphere jdbc datasource to execute a statement like `SELECET 1`. The verification SQL for each database is different, and the verification SQL has nothing to do with the database gateway of shardingsphere.

**Comment by terrymanu** [comment]
The title of this issue is not well enough, could you please update to a more understandable title by summarizing the content?
