### ISSUE TITLE
How to get the real db and table name after sharding and record it in the log of other frameworks

### ISSUE THREAD

**Issue by jyyfei** [apache/shardingsphere#32801]
## Question

I use mybatis interceptor for sql statistics, but only logical DB and table name are displayed in sql, how to gracefully obtain the physical DB and table name after sharding processing？

Or whether sharding itself provides an interceptor extension？

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
