### ISSUE TITLE
Does the new version support JDK17 and JDK21?

### ISSUE THREAD

**Issue by NicknameZZ** [apache/shardingsphere#32822]
Does version 5.4 or 5.5 support JDK17 and JDK21?

**Comment by linghengqian** [comment]
- CI covers `JDK8` - `JDK22`, so the answer to your question is obviously yes. 
- By the way, JDK24 currently has breaking changes, which is not something that shardingsphere can solve, and you need to wait for the OracleLabs side to synchronize the changes.

**Comment by linghengqian** [comment]
- As a supplement,
    - JDK 17 has been in CI for several years.  
    - ShardingSphere 5.4.1 starts to support OpenJDK 21. Refer to #28326 .
    - ShardingSphere 5.5.0 starts to support OpenJDK 22. Refer to #30778 .
    - Once OpenJDK 23 is officially released, we can verify the availability of Hotspot JDK and GraalVM Native Image in the master branch. The release of ShardingSphere 5.5.1 does not necessarily wait for the release of OpenJDK 23.

- Obviously, these commits will not return to the old versions that are no longer maintained.

**Comment by NicknameZZ** [comment]
> * As a supplement,
>   
>   * JDK 17 has been in CI for several years.
>   * ShardingSphere 5.4.1 starts to support OpenJDK 21. Refer to [Support for building with OpenJDK 21 #28326](https://github.com/apache/shardingsphere/pull/28326) .
>   * ShardingSphere 5.5.0 starts to support OpenJDK 22. Refer to [Support building ShardingSphere and its corresponding GraalVM Native Image through JDK 22 #30778](https://github.com/apache/shardingsphere/pull/30778) .
>   * Once OpenJDK 23 is officially released, we can verify the availability of Hotspot JDK and GraalVM Native Image in the master branch. The release of ShardingSphere 5.5.1 does not necessarily wait for the release of OpenJDK 23.
> * Obviously, these commits will not return to the old versions that are no longer maintained.

By the way,  is the 5.5.0/5.4.1 compatible with JDK8？

**Comment by linghengqian** [comment]
> > * As a supplement,
> >   
> >   * JDK 17 has been in CI for several years.
> >   * ShardingSphere 5.4.1 starts to support OpenJDK 21. Refer to [Support for building with OpenJDK 21 #28326](https://github.com/apache/shardingsphere/pull/28326) .
> >   * ShardingSphere 5.5.0 starts to support OpenJDK 22. Refer to [Support building ShardingSphere and its corresponding GraalVM Native Image through JDK 22 #30778](https://github.com/apache/shardingsphere/pull/30778) .
> >   * Once OpenJDK 23 is officially released, we can verify the availability of Hotspot JDK and GraalVM Native Image in the master branch. The release of ShardingSphere 5.5.1 does not necessarily wait for the release of OpenJDK 23.
> > * Obviously, these commits will not return to the old versions that are no longer maintained.
> 
> By the way, is the 5.5.0/5.4.1 compatible with JDK8？

- For any shardingsphere version, you need to compile with `JDK11`-`JDK22`, but the product can always run on `JDK 8`. This is because `JDK11` is required by Antlr 4 compiler.  Antlr 5 does not provide Java support yet, and ShardingSphere does not use Antlr 5 to write rules for parsing SQL.
- The only exception is GraalVM Native Image. To use ShardingSphere JDBC under GraalVM Native Image, you need `GraalVM CE For JDK 22.0.2` or higher to compile the corresponding product, which is a requirement of `apache/hive`. According to the release cycle of OracleLabs, ShardingSphere will only support compilation through `GraalVM CE For JDK 23` or `GraalVM CE For JDK 24` in the next few months. `GraalVM CE For JDK 23` has very breaking changes around the GraalVM Native Image.

**Comment by linghengqian** [comment]
- Issue closed due to no response.
