### ISSUE TITLE
shardingSphere-jdbc version 5.5.0,the tables without encryption rules will report an error,'Table or view 'xxx' does not exist.'

### ISSUE THREAD

**Issue by jiusi-yyq** [apache/shardingsphere#32863]
<img width="450" alt="image" src="https://github.com/user-attachments/assets/dba0e89b-3900-42b2-83ed-d3d8df43eef2">

The encrypted table query is correct，but If I query data from another table,such as user_extra（PS：the table does‘t need  encryption, therefore  no encryption rules have been configured）

Result is an error：Caused by: org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 'user_extra' does not exist.

shardingSphere-jdbc 5.5.0
Springboot 3.1.8
mybatis 3.0.2

**Comment by limng06** [comment]
rules:
  - !SINGLE
    tables:
      - "*.*"  
add user_extra to single table

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.

**Comment by jiusi-yyq** [comment]
ok thanks. 
<img width="578" alt="image" src="https://github.com/user-attachments/assets/f3d3a454-8ee4-4ecf-9d89-2bb9c7c53111">

**Comment by jiusi-yyq** [comment]
ok thanks. 
<img width="579" alt="image" src="https://github.com/user-attachments/assets/88866f2f-b93d-49f1-8cc5-ea47ea311e53">

**Comment by jiusi-yyq** [comment]
resolved

**Comment by 15102552479** [comment]
> resolved

please,I just used the encryption function and upgraded from version 5.2.1 to 5.5.0. I have the same problem as you. Help
