### ISSUE TITLE
Does Shardingsphere-proxy currently support integration with Seata?

### ISSUE THREAD

**Issue by 26903651** [apache/shardingsphere#33791]
Does Shardingsphere-proxy currently support integration with Seata? The official documentation only seems to have information on integrating Shardingsphere-jdbc with Seata. If it is possible to integrate Shardingsphere-proxy with Seata, are there any relevant documents or examples available?

**Comment by terrymanu** [comment]
It supports the early Seata version, but no time to integrate the newest version for now.

**Comment by 26903651** [comment]
> It supports the early Seata version, but no time to integrate the newest version for now.

Could you please tell me which version of Seata is compatible with ShardingSphere-Proxy? Is there any relevant documentation?

**Comment by terrymanu** [comment]
FYI: https://github.com/search?q=repo%3Aapache%2Fshardingsphere+seata+language%3A%22Maven+POM%22&type=code&l=Maven+POM

**Comment by 26903651** [comment]
I'm sorry, after entering this link, I did not find any examples on how to integrate ShardingSphere-Proxy with Seata. Could you tell me more please?

**Comment by linghengqian** [comment]
@26903651 
- What I can tell you clearly is that a lot of unit tests for shardingsphere's seata integration are not actually in shardingsphere's master branch because https://github.com/apache/incubator-seata/issues/6614 is not resolved. 

1. Shardingsphere jdbc's seata integration and seata client 2.2.0 can be used under both HotSpot VM and GraalVM Native Image. 

2. Shardingsphere proxy's seata integration and seata client 2.2.0 can be used under HotSpot VM, but have not been tested under shardingsphere proxy native under GraalVM Native Image. The reason why the relevant unit tests are not in shardingsphere's master branch is that https://github.com/apache/incubator-seata/issues/7039 is not resolved.

- In order to support GraalVM Native Image, all ShardingSphere support for Seata Client 1.x has been abandoned. See https://github.com/apache/shardingsphere/issues/29052 ,  https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/transaction/seata/ and [跨越 MySQL 边界 -- GraalVM Native Image 下 ShardingSphere JDBC 的 Seata AT 集成 https://www.yuque.com/linghengqian/meve2v/es8d3a8a18odao7x](https://www.yuque.com/linghengqian/meve2v/es8d3a8a18odao7x) .
- Back to the current issue, there is actually not much to do except updating the documentation.
- Of course, in order to further resolve the dependency conflicts of Seata Client, I tend to change the seata client used by shardingsphere for testing from 2.1.0 to 2.2.0 . We all know that the Docker Image of Seata 2.2.0 currently has 593 CVEs, which means we need to speed up. See https://github.com/oracle/graalvm-reachability-metadata/issues/542#issuecomment-2446645418 .
