### ISSUE TITLE
Unknown exception: All tables must be in the same datasource.

### ISSUE THREAD

**Issue by zhuzhiquan** [apache/shardingsphere#33873]
## Question

A table is associated with B table query. A has performed table splitting operation, but B has not. At this time, the associated query prompt: Unknown exception: All tables must be in the same data source. How to solve the error?

**Comment by terrymanu** [comment]
What is your version?

**Comment by zhuzhiquan** [comment]
5.2.1

**Comment by terrymanu** [comment]
What is your configuration?

**Comment by zhuzhiquan** [comment]
![配置](https://github.com/user-attachments/assets/4e8bddb8-b229-4abf-b9f1-b8c59d99b033)
Like the picture ，How should I configure based on version 5.2.1?

**Comment by zhuzhiquan** [comment]
By the way, can a single table be queried by associating it with a sharded table?

**Comment by terrymanu** [comment]
The issue contains only images, which is not conducive to search or code copying by contributors. Could you please recreate an new issue and describe it again using text and code?

**Comment by zhuzhiquan** [comment]
[application123.txt](https://github.com/user-attachments/files/18032274/application123.txt)
At this point, when t_navigation is associated with a single table, it will prompt:All tables must be in the same datasource

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
