### ISSUE TITLE
shardingSphere-jdbc，the query conditions of the sql missing，cause the Result is incorrect

### ISSUE THREAD

**Issue by jiusi-yyq** [apache/shardingsphere#33895]
shardingSphere-jdbc：5.3.2
mysql-connector：8.0.33

Actual SQL: unique_ds ::: SELECT  id,expired,channel_id,channel_apply_id,qts_apply_id,part_job_id,mobile AS mobile,name,apply_remark,school_name,sex,diploma,birthday,wechat,qq,mail,introduction,status,callback_status,reason,account_id,user_id,major,part_job_experience,tags,town,job_intention,apply_content,pro_skill,create_time,update_time  FROM open_channel_job_apply      WHERE  (channel_id = ? AND expired = ? AND channel_apply_id = ?) ::: [241105144043504, false, AP7285393762536287916]

Logic SQL: SELECT  id,expired,channel_id,channel_apply_id,qts_apply_id,part_job_id,mobile,name,apply_remark,school_name,sex,diploma,birthday,wechat,qq,mail,introduction,status,callback_status,reason,account_id,user_id,major,part_job_experience,tags,town,job_intention,apply_content,pro_skill,create_time,update_time  FROM open_channel_job_apply      WHERE  (channel_id = ? AND expired = ? AND channel_apply_id = ?)

the error：
![image](https://github.com/user-attachments/assets/060aa74d-abe1-4cb1-aa67-f6dea2da855b)

the reason is the channel_apply_id condition missing  during sql run。

the problem don't certainly occur，which is occasional. especially，the problem easily occur during large Request quantity.

**Comment by aillamsun** [comment]
there are significant differences between versions, and there are many compatibility issues

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
