### ISSUE TITLE
use pagehelper and shardingsphere5.5.0 cause pagehelper PageAutoDialect failed

### ISSUE THREAD

**Issue by appleqc** [apache/shardingsphere#34105]
Recently, I upgraded Shardingsphere to 5.5.0 using springboot3 and Pagehelper in my project, which caused Pagehelper to be unable to parse out the dialogue during pagination processing, resulting in an error. After a simple investigation, I found that Pagehelper was using Spring. Data Source. URL to parse which database to use. Due to the configuration of the new version of Shardingsphere, the URL has been changed, causing the parsing to fail. Is there any good way to handle this issue? If you encounter a similar problem, please specify it, my database is mysql
![image](https://github.com/user-attachments/assets/9150ae2e-f8e2-43e7-929e-2024f838b686)

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
