### ISSUE TITLE
Is seata.conf required?

### ISSUE THREAD

**Issue by romantictravel01** [apache/shardingsphere#5293]
## Question
version:4.0.1
env: mybatis-plus+spring cloud+seata 
       Seata can be configured in application.yml, but shardingsphere must be configured with seata.conf

**Comment by kimmking** [comment]
remove seata-starter and use seata.conf.

**Comment by cherrylzhao** [comment]
seata.conf is required when you want use `sharding-transaction-base-seat-at` to guarantee distribute-transaction within shardingpshere. if you want to guarantee distribute-transaction within micro-service together with shardingpshere, both Seata.conf and `sharding-transaction-base-seata-at` is not needed, which will be supported since 4.1.0

**Comment by fengyunhe** [comment]
Hi, @kimmking   

```
client {
    application.id=study-sharding-jdbc
    transaction.service.group = my_test_tx_group
}
```
what is transaction.service.group , if i use a value not is `my_test_tx_group` then get error ,but use value is `my_test_tx_group`, then get successful.

**Comment by kimmking** [comment]
@fengyunhe 
https://seata.io/zh-cn/docs/user/configurations.html

**Comment by fengyunhe** [comment]
@kimmking  thank you
