### ISSUE TITLE
[To anyone who has similar questions] I follow you

### ISSUE THREAD

**Issue by 65725738** [apache/shardingsphere#5971]
不得不吐槽。中国人写的，非要用英文发帖。
东西写的好，还怕没人用，整那么多幺蛾子干嘛。中国市场足够大，满足国内市场在看国外吧。
从大的方面来说，我们的目标是推广中文，让别人学中文来看我们的技术。我们不能靠茅台，要考技术强国，你们这些大牛应该担起责任。

版本乱七八糟，同样的代码，同样的配置，4.0.0-rc2 不能用 4.0.1 可以用 4.1 又不能用。

也没有什么说明。

完全不知道在搞什么

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by tristaZero** [comment]
Hi,

Actually, I hesitate to respond or not at first glance, since maybe It is no meaning to discuss why people have to talk with others in English in an Apache project community (**Apache ShardingSphere must conform to the regulation of Apache, speaking in English is included**).

Secondly, **English is a universal language**, only in which people all over the world could learn more about Apache ShardingSphere better.

Thirdly, I am sorry for the changed APIs among different release versions, which I know is not friendly for users to upgrade. But the purpose that the whole community works hard is to provide a better, stable, and foresighted product. Frankly speaking, ShardingSphere is not so perfect since it is underway. But that is exactly what we are working on, i.e., **The API of 5.x release will settle down and provide a much simpler configuration for our community**.

Last but not least, I can't entirely agree with your opinion. Apache ShardingSphere is open source and free for everyone. **You do need to pay nothing to use it, why do you only judge it? If you think it not so good, why do not you join this community to improve it and make it become what you want it to be?** You know it is also a chance to start your open source journey, and others could benefit from what you did as well!

If one person wants to become professional and influential(Maybe), or just out of his or her interests, it is a great way to join an open-source community and try to make some contributions. I believe.

Best,

Trista

**Comment by tristaZero** [comment]
Sorry, I will close this ISSUE in 7 days.
