### ISSUE TITLE
ERROR Maxwell - SQLException: No database selected

### ISSUE THREAD

**Issue by ChuckPerry** [apache/shardingsphere#6061]
## Bug Report
> ERROR Maxwell - SQLException: No database selected

When I use shardingproxy connect maxwell , It throw this error ,and maxwell could not start 
When I use proxysql or mysql cli connect maxwell, It run OK. 
### Which version of ShardingSphere did you use?
Mysql version: 5.7.21
Maxwell version: 1.26.4
Shardingproxy version: 4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### step as below

` ./maxwell --client_id="maxwell" --user='maxwell' --host='xx.xx.xx.11' --password="xxxxxxx" --port='23306' --log_level=DEBUG --producer=stdout --filter=exclude:*.*,include:db1.tb1.*`

> Using kafka version: 1.0.0
11:11:45,421 ERROR Maxwell - SQLException: No database selecte

**Comment by kimmking** [comment]
you should set databaseName with command line option.

**Comment by ChuckPerry** [comment]
I set the db name through two params: client_id or schema_database
but It help nothing.

**Comment by kimmking** [comment]
can you use mysql-cli connect sharding-proxy？

**Comment by ChuckPerry** [comment]
> can you use mysql-cli connect sharding-proxy？
yes, I can.
`# mysql -umaxwell -p -hxx.xx.xx.11 -P23306 maxwell`
`Logging to file '/usr/local/mysql/mysql_client.log'`
`Enter password:`
`mysql> show tables;`
`+-------------------+`
`| Tables_in_maxwell |`

**Comment by xlxomg** [comment]
I had this problem too, and it happened occasionally  (Shardingproxy version: 4.1.1)

**Comment by xlxomg** [comment]
I found the general reason. I used Navicat for mysql 12, and I can connect again after I restart Navicat, or I can connect with mysql command (translation software).

**Comment by tuohai666** [comment]
@ChuckPerry Can you use wireshark to capture the process?

**Comment by tuohai666** [comment]
@ChuckPerry @xlxomg This problem may be resolved by https://github.com/apache/shardingsphere/pull/7182 . Can you try with 5.0.0-RC1-SNAPSHOT in master branch?

**Comment by xlxomg** [comment]
Sorry, I can't help you.This problem is not 100% reproducible, and I don't have much time.(Translation software)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhang Yonglun"<notifications@github.com&gt;; 
发送时间: 2020年8月31日(星期一) 晚上7:50
收件人: "apache/shardingsphere"<shardingsphere@noreply.github.com&gt;; 
抄送: "谢璐鑫、"<353018992@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/shardingsphere] ERROR Maxwell - SQLException: No database selected (#6061)





 
@ChuckPerry @xlxomg This problem may be resolved by #7182 . Can you try with 5.0.0-RC1-SNAPSHOT in master branch?

**Comment by tuohai666** [comment]
@xlxomg Thanks all the same.

**Comment by tuohai666** [comment]
Duplicated with #7141 .
