### ISSUE TITLE
Optimize startup time， control which tables can load when startup

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#6212]
I find the startup time is too slow due to the database full tables metadata scan,  
for our case. the database has 200 tables, we are using micro service, one app loads about 10-20 tables,  it's not acceptable to load all tables on startup

tuohai666:

We have received several similar reports about the slow startup recently, mostly due to loading unconfigured tables for meta data purpose of ShardingSphere.

https://github.com/apache/shardingsphere/issues/6179 : 7000+ tables cost much time.
Similar issues: https://github.com/apache/shardingsphere/issues/6161 , https://github.com/apache/shardingsphere/issues/5755 , https://github.com/apache/shardingsphere/issues/5999 .

Loading table (column and index information) is expensive, there're 7 SQLs interactive for each table.
![image](https://user-images.githubusercontent.com/24643893/86317891-24003900-bc63-11ea-9bb9-9d6ffbaa0316.png)

After investigate, I found that for tables unconfigured will not use column or index information any more after loading. So we can omit this process. 

I also checked the relevant issue https://github.com/apache/shardingsphere/issues/4460 , which will load collation for all columns in every table. If a table is unconfigured, the route result must be single route, a single route will not need merge any more. If the resultset does not need to merge, it is irrelevant with cache of collation. So I think we can safely remove the loading of unconfigured tables now.

Note that all unconfigured table names still need to be loaded for routing logic, this can simply obtain from one SQL for each database.

We can accomplish the goal by several steps.

- [ ] Remove the load procedure for unconfigured tables.
- [ ] Remove the refresh procedure for unconfigured tables
- [ ] Remove the multi-thread logic for unconfigured tables. (Configured tables still use multi-thread)
- [ ] Load table names for unconfigured tables.
- [ ] Sync up the new load logic with orchestration module.
- [ ] Update the unit test cases.

**Comment by tuohai666** [comment]
I am focused on this problem too. You can refer to https://github.com/apache/shardingsphere/issues/6179 .

Any idea?

**Comment by xbkaishui** [comment]
**I think we can solve this in two ways:** 
1. for my case, one app load few tables,  can we just add a config to specify which tables want to load
2. another way is can we use lazy load, I means loading table metadata we first used,  for the lazy load, this will be affect the performance for the first sql execution , this will be a trade off

**Comment by xbkaishui** [comment]
I prefer the second solution,  lazy load

**Comment by kimmking** [comment]
few tables metadata or lazy-load, all lead to the one of :
1、unconsistent metadata status
2、pending first query for metadata load

**Comment by xbkaishui** [comment]
for the single table metadata load, most of the latency time with be 1-4ms,  for most case I think it is ok. 
for the inconsistent metadata status,  it is acceptable 

can we make the table load policy multi choose for user, not just load all tables, 
this is also unacceptable in service mesh scene, which required elastic scale in and out.

**Comment by xbkaishui** [comment]
any update guys ?

**Comment by tuohai666** [comment]
We have received several similar reports about the slow startup recently, mostly due to loading unconfigured tables for meta data purpose of ShardingSphere.

https://github.com/apache/shardingsphere/issues/6179 : 7000+ tables cost much time.
Similar issues: https://github.com/apache/shardingsphere/issues/5755 , https://github.com/apache/shardingsphere/issues/5999 .

Loading table (column and index information) is expensive, there're 7 SQLs interactive for each table.
![image](https://user-images.githubusercontent.com/24643893/86317891-24003900-bc63-11ea-9bb9-9d6ffbaa0316.png)

After investigate, I found that for tables unconfigured will not use column or index information any more after loading. So we can omit this process. 

I also checked the relevant issue https://github.com/apache/shardingsphere/issues/4460 , which will load collation for all columns in every table. If a table is unconfigured, the route result must be single route, a single route will not need merge any more. If the resultset does not need to merge, it is irrelevant with cache of collation. So I think we can safely remove the loading of unconfigured tables now.

Note that all unconfigured table names still need to be loaded for routing logic, this can simply obtain from one SQL for each database.

**Comment by tuohai666** [comment]
We can accomplish the goal by several steps.

- [ ] Remove the load procedure for unconfigured tables.
- [ ] Remove the refresh procedure for unconfigured tables
- [ ] Remove the multi-thread logic for unconfigured tables. (Configured tables still use multi-thread)
- [ ] Load table names for unconfigured tables.
- [ ] Sync up the new load logic with orchestration module.
- [ ] Update the unit test cases.

**Comment by xbkaishui** [comment]
ok got it

**Comment by tuohai666** [comment]
After more test and investigate, we found that this issue can't be fixed for now.

The pr(https://github.com/apache/shardingsphere/pull/6247/) shows that if SELECT from an unconfigured table or a MasterSlaveRule table, result table meta data will be null, and shardingsphere-proxy can't return the result, shardingshpere-jdbc will also meet problem.

That's because QueryHeader in proxy is processed by ProjectionsContext after https://github.com/apache/shardingsphere/pull/4657 . ProjectionsContext process QueryHeader depends on the column information obtained from the table loading when application startup.

It looks like we must load column information for unconfigured tables. More details please refer to: https://github.com/apache/shardingsphere/issues/4637

**Comment by tristaZero** [comment]
Hi, community,

Since this issue seems a serious one, we will consider other solutions trying to solve it. I will take charge of it later.

**Comment by tristaZero** [comment]
### Backgroud

ShardingSphere is aiming at simplifying the configuration workload and placing itself as `distributed-database` as possible to help users manage all the tables (no matter whether it is a sharding table or not).

It is better for users to **use ShardingSphere and do not care about** sharding tables, non-sharding tables, encrypted tables, etc. But some configurations are necessary. :)

Based on that, we have to load metadata from all the tables. This issue is to **speed the metadata loading**. 

### Solution

After some of the researches, we propose another solution to solve this issue.

Currently, **a rough solution** is that we can load metadata through [information_schema](https://en.wikipedia.org/wiki/Information_schema) from different databases. (Thanks for your work! @tuohai666  )

Specifically, we do some queries from `information_schema`  and skip JDBC' call for databases. In addition, the JDBC loading method **will remain** for conservative treatment.

### Plan
In the beginning, I will design the basic framework and interfaces and implement `MySQL` loading process. Then, we will ask our community for help to implement `PostgreSQL`, `Oracle`, `SQLServer`, and `H2`. Looking forward to your involvement!

Last but not least, **welcome your discussion and thoughts about this issue and solution**!

**Comment by tristaZero** [comment]
Hi everyone,

I intend to shift some of my focus on this issue. As you know, [Information_schema](https://github.com/apache/shardingsphere/issues/6212#issuecomment-665589111) is the most effort-taking and the last way for us to achieve this optimization.
After my crude investigation, I feel that it is feasible to only load the column metadata for configured tables and table names for unconfigured tables. 
However, some of the decoupling work is needed to be done before that. I will finish this one ASAP. Moreover, @xbkaishui would you like to restart our previous plan and try your best to make #6247 merged? I believe you are the right one for that, also I'd like to listen to your thinking. :-)

Looking forward to your feedback.

Best,
Trista

**Comment by xbkaishui** [comment]
@tristaZero , Yes I am very appreciate for this task.

**Comment by lunarzzz** [comment]
hi, can i get this alpha version from maven center repo?

**Comment by tristaZero** [comment]
> hi, can i get this alpha version from maven center repo?

We released 5.0.0-alpha a few days ago; I guess it is in maven repo now but still need your try.

**Comment by zhangdc007** [comment]
sharding-jdbc-spring-boot-starter still in 4.1.1

**Comment by zhangdc007** [comment]
> > hi, can i get this alpha version from maven center repo?
> 
> We released 5.0.0-alpha a few days ago; I guess it is in maven repo now but still need your try.

sharding-jdbc-spring-boot-starter still in 4.1.1,and 
<dependency>
  <groupId>org.apache.shardingsphere</groupId>
  <artifactId>shardingsphere-sharding-spring-boot-starter</artifactId>
  <version>5.0.0-alpha</version>
</dependency>
config is different with 4.1.1
