### ISSUE TITLE
The closing delete/modify dataSource process in OrchestrationShardingDataSource#renew(DataSourceChangedEvent)

### ISSUE THREAD

**Issue by ananbeike** [apache/shardingsphere#6231]
shardingsphere version: 4.0.1
register/config center: zookeeper

After modifying the configuration of the data source, [OrchestrationShardingDataSource#renew(DataSourceChangedEvent)] method  will be triggered.
```
    @Subscribe
    @SneakyThrows
    public final synchronized void renew(final DataSourceChangedEvent dataSourceChangedEvent) {
        Map<String, DataSourceConfiguration> dataSourceConfigurations = dataSourceChangedEvent.getDataSourceConfigurations();
        dataSource.close(getDeletedDataSources(dataSourceConfigurations));
        dataSource.close(getModifiedDataSources(dataSourceConfigurations).keySet());
        dataSource = new ShardingDataSource(getChangedDataSources(dataSource.getDataSourceMap(), dataSourceConfigurations), 
                dataSource.getRuntimeContext().getRule(), dataSource.getRuntimeContext().getProps().getProps());
        getDataSourceConfigurations().clear();
        getDataSourceConfigurations().putAll(dataSourceConfigurations);
    }
```

### Question
1. Why not wait there are no active connections in the datasource before closing ;Now if simple close the datasource there will be exception ;
2. If we want to close the datasource util there are no active connection,do you have any suggestions?

Thanks.

**Comment by kimmking** [comment]
1. lead to pending all query before new datasource instead of old one
2. it's more complex for graceful shutdown/refresh, 
- close old ds to be an easy way to implement
- pend all new query and wait existing connection release and close completely to a short time unavailable
- keep old ds not accept new query and wait for closing completely, and the same time create a new ds to accept new query to be a better way, but it's hard to implement
