### ISSUE TITLE
about performance test

### ISSUE THREAD

**Issue by lishijun121910** [apache/shardingsphere#6501]
![image](https://user-images.githubusercontent.com/8045307/88763611-006ad880-d1a6-11ea-9b14-686377570c0c.png)

the performance test result above(from official document,) is not very stable, which part should we look and consider?

**Comment by kimmking** [comment]
It's the develop branch, not release version.

**Comment by tristaZero** [comment]
@lishijun121910 Hi
Thanks for the feedback.
I am sorry that we are working on the performance test. Due to that, you got this strange graph.
But currently, our performance test shows a better performance at 10 million data volume. Please wait for our farther testings.

Besides,, [other teams](https://github.com/wangshuzheng/sharding) are doing ShardingSphere test.
