### ISSUE TITLE
The timing of Hint's use

### ISSUE THREAD

**Issue by peng-ran** [apache/shardingsphere#6548]
Do you have any good Suggestions on the timing of setting Hint and releasing Hint?I don't want to do AOP interception with annotations because it would be too intrusive for your code.

**Comment by peng-ran** [comment]
How to parse the sub-table on the callback algorithm, skipping the hint, sharding value will be managed in my program, no need to provide sharding-JDBC, if I use hint, I have to set it every time I execute SQL, because no setting will not trigger the algorithm callback

**Comment by kimmking** [comment]
Can you show a concrete scenario？

**Comment by peng-ran** [comment]
@kimmking 
I'm on the outside of the program, maintained the shard of tenants and database, table routing relationship, when sharding - JDBC in analytic to SQL table callback fired when algorithm, I, a logical table based on routing table and fact table match, so I don't need to give sharding - JDBC defines all of the tables, and there is no scene every time executing SQL sets the hint, I understand that I only need a SQL parsing table after the callback.

**Comment by peng-ran** [comment]
Following the Sharding-JDBC approach, I now have to define all tables (because normal tables may be sharding-dababase) and have to intercept all persistent methods for set hint

**Comment by tristaZero** [comment]
@peng-ran Sorry I did not catch you. 
You do not want to set `hint manager` every time you execute SQL?

**Comment by peng-ran** [comment]
@tristaZero  
Yes, sharding doesn't need to be calculated, I have a mapping, I just want to be able to fire the algorithm class when Sharding-JDBC parses the logical table in SQL.

**Comment by tristaZero** [comment]
If users do not set sharding key to `hint manager`, how do users tell the specific values of sharding key to sharding JDBC.
Do you have any other better ideas?

BTW, I guess you wrote comments with the help of Google or Baidu translation tools, didn't you? I suggest you review these translation scripts firstly since this translation confused me a lot. If I could not catch what you said, I would not give you any answers, right?

@peng-ran

**Comment by peng-ran** [comment]
@tristaZero 

抱歉， 我用翻译软件和您交流的，因为英语不好，又希望和各位交流下想法，请原谅我使用中文。

我的问题是这样的，我的SQL中没有分片字段，分片规则是按照我自己维护的路由映射关系加载到程序的全局中定义好的，比如数据库A，路由至库A_10002，表也如此，同时，大部分表是不需要分表的，基于此背景，应用sharding-jdbc后发现下面两个问题：

1. 不需要分片的表也需要定义，否则当SQL中只有未分片的表时，只会使用默认数据源，可是我需要把他路由到分库上

2. 我必须AOP拦截所有SQL操作，否则没有设置Hint的时机，不设置Hint就无法触发HintShardingAlgorithm的回调。分片值我也是随便塞的，

其实我需要的只是每次执行SQL，sharding-jdbc都能回调下，我会返回事实库名称，SQL解析到设置分片的表时也能回调下，我会返回事实表名 即可。

**Comment by tristaZero** [comment]
Hi @peng-ran Sorry, we have to talk in English since this is an international Apache community.
1. You can configure non-sharding-table with `NoneShardingStrategy and actual dataNode`.
2. As I said before, If users do not set sharding key to hint manager, how do users tell the specific values of sharding key to sharding JDBC. Do you have any other better ideas?
