### ISSUE TITLE
Update release process, do not publish proxy jar into maven repository

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6870]
We publish proxy's jar into maven repository which does not make sense.
It is better publish jdbc's jar to maven repository only.
We can reference UI' release process.

**Comment by tuohai666** [comment]
@terrymanu 

I have checked the repo (https://repository.apache.org/). For legacy version (4.0.0 RC1 ~ 4.0.0), there're Sharding-Proxy's jar. But there's no ShardingSphere-Proxy's jar for new versions yet. 

We have set `<maven.deploy.skip>true</maven.deploy.skip>` for ShardingSphere-Proxy module since 4.1.0. So there're no jar for proxy in 4.1.0/4.1.1 and the following 5.0.0-RC1.
