### ISSUE TITLE
How can we apply ShardingSphere for Decentralised Databases?

### ISSUE THREAD

**Issue by gokulsan** [apache/shardingsphere#6957]
I would like to scale decentralized databases such as OrbitDB, GunDB, etc. using Apache Sharding Sphere. These decentralised databases have redundant database nodes acting as replicated state machines. Is it feasible with Sharding Sphere?

**Comment by tristaZero** [comment]
Hi @gokulsan, Thanks for your attention.

Since I am not familiar with `OrbitDB`or `GunDB`, I am not sure whether my explanation is accurate. If I miss something, welcome your comment.

Actually, the main aim of `Apache ShardingSphere` is to make the traditional DBMS like `MySQL`, `PostgreSQL`, `Oracle`, `SQLServer` has the scalability or turn them to `distributed databases`.
Base on that, my answer is `NO`. Here is my explanation.

1. SQL. I presume that traditional SQLs do not apply to `OrbitDB`or `GunDB`, right?  But SQL is the communication language between clients and ShardingSphere.
2. Programing language or protocol. There are two products of `ShardingSphere` for you to choose. `ShardingProxy` is like an enhanced `MySQL` or `PostgreSQL` server, then the binary proposal is used for visiting. On the other hand, `ShardingJDBC` is a lightweight JAVA framework, hence JAVA language is required.
3. I can not catch your thought. AFAIK, `Decentralised Databases` have the scalability or `distributed storage` already, so users do not need to care about `storage capacity` or `query efficiency`. So why do you want to use `ShardingSphere` for `Decentralised Databases`?

**Comment by tristaZero** [comment]
Hi @gokulsan 

Sorry for my late response. :-)
You are right, `distributed data synchronization` is another unavoidable topic for these distributed database middlewares. Considering the `data consistency`, IMO, there are two issues, i.e., `distributed transaction` for applications and `distributed storage` for there distributed databases themselves.
For the first one, `2PC` or `B.A.S.E` distributed transaction solutions are our concerns and developing currently.
But concerning the second one, if it is a distributed database `proxy or middleware`, then like MySQL replication between the master node and slave nodes can help a lot. On the other hand, if it is a real `distributed database`, then a distributed storage is supposed to come together accordingly. 
However, ShardingSphere is more like a distributed database `proxy or middleware ecosystem`. Hence I have to say we did a tradeoff between `data consistency` and `scalability and query efficiency`.

Cheers,
Trista

**Comment by kimmking** [comment]
Just like @tristaZero explaination above.
ShardingSphere is based on RDBMS, but OrbitDBor/GunDB is based on blockchain, they are not compatible yet.
