### ISSUE TITLE
Sharding rule question

### ISSUE THREAD

**Issue by goool** [apache/shardingsphere#7563]
There are there tables: A, B, and C, and two FOREIGN KEY constraint between them.

        B.a_id references A.id  
        C.b_id references B.id  

I use sharding-proxy to partition the data to different databases.

Can anyone help me, how do I configure sharding rules, so that three related data records, goes to the same database.

**Comment by kimmking** [comment]
Use the same sharding stategy for the ABC tables and binding them.
- A.id modify to a_id,
- add a_id to table C,
- use a_id as the database sharding-key and binding ABC

**Comment by goool** [comment]
Thanks for the reply. My actual situation is that the mysql database already has a lot of data, I can't change the column names or add new columns.

**Comment by tristaZero** [comment]
Hi @goool 

First, the `bind table` setting could make two or more `logic` tables share the same distribution of their own actual tables.
Second, I can not get your concern about `bind tables` from `I can't change the column names or add new columns.` Since `sharding column` is indispensable for any `logic table` with shards.
