### ISSUE TITLE
Support for Spring Data JPA needs to be added

### ISSUE THREAD

**Issue by 474846718** [apache/shardingsphere#7575]
Use JPA spring.jpa.hibernate.ddl-auto feature to achieve zero configuration for direct use.

**Comment by yu199195** [comment]
whats you mean？

**Comment by tristaZero** [comment]
Hi @474846718 Thanks for your idea. 
> spring.jpa.hibernate.ddl-auto

Does that mean ShardingSphere helps users create sharding tables automatically? In that case, the sharding rule is also necessary; otherwise, ShardingJDBC does not know how to shard tables.

BTW, a similar feature for ShardingProxy will be online soon! Users can start ShardingProxy without sharding rules and create Sharding tables by SQL. [RDL feature](https://github.com/apache/shardingsphere/issues/7324) will present you with more details.

**Comment by kimmking** [comment]
see https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application.properties
