### ISSUE TITLE
New independent SQLParserEngine is going online to parse SQL for different database dialects

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#7869]
Hi community,

I am glad to announce that ShardingSphere will provide an independent SQL parser engine for parsing SQLs!
I believe you will have some of the scenarios or use the SQL parser engine to get a parsed AST. From now on, you will have another option for your cases. Here are some of the advantages for ShardingSphere parser engine.

### Advantages
-  Mostly perfect SQL statements supported for MySQL database
-  Mostly perfect SQL statements supported  for PostgreSQL database
-  Basically SQL statements supported  for SQLServer database
-  Basically SQL statements supported  for Oracle database
-  Basically SQL statements supported  for SQL92
-  SQL parsed result cache for the parsing performance
-  AST parsed result and SQLStatement parsed result are provided meanwhile
-  Simple extension approach for SQLStatement visitors
-  Simple supplement approach and for SQL definition 
-  Continuous improvement for the much better feature in the future.

5.x release will include this one, please wait for our good news! 😉

**Comment by yangtaihsou** [comment]
I claim this issue.

**Comment by khalidcawl** [comment]
Hi @tristaZero. I came across this comment (and this repository) just now while searching for a SQL-92 parser. Is it supported in the SQLASTParserEngine? My use case is very simple: 
Input: SQL-92 compliant SQL
output: extract Tables and Columns in the SQL

I would appreciate if you could point me to where I could get started. 
Thanks in advance.

**Comment by tristaZero** [comment]
Hi @khalidcawl Sorry for my late reply.

Thanks for your remainder. The answer is YES. As I mentioned in this issue, `Basically SQL statements supported for SQL92` is in this release range. But I suggest you'd better give it a test. :)
And we will provide the detailed instruction later. If you can not wait to use, packaging the master branch is needed for you.

Best,
Trista

**Comment by tristaZero** [comment]
Hi, community,

There is an important discussion about our user API  for the SQL parser engine. Your opinion will have a direct impact on the final API for this incoming feature. We'd like to listen to your any of comments and ideas!

Here are two API usage ways in consideration. Which one is your preference and why? Welcome comment below with your thinking!

```java
public static void main(String[] args) {
    String dbType = "MySQL";
    String visitorType = "SQLStatement";
    boolean useCache = true;
    
    String sql1 = "select * from tb1";
    String sql2 = "select * from tb2";
    
    
    // Way1
    ParseTree ast1 = SQLParserEngine.parse(dbType, sql1, useCache);
    SQLStatement result1 = SQLVisitorEngine.visit(dbType, visitorType,  ast1);
    
    ParseTree ast2 = SQLParserEngine.parse(dbType, sql2, useCache);
    SQLStatement result2 = SQLVisitorEngine.visit(dbType, visitorType,  ast2);
    
    // Way2
    SQLParserEngine parser = new SQLParserEngine(dbType);
    SQLVisitorEngine visitor = new SQLVisitorEngine(dbType,  visitorType);
    
    SQLStatement result1 = visitor.visit(parser.parse(sql1,  useCache));
    SQLStatement result2 = visitor.visit(parser.parse(sql2,  useCache));
}
```

**Comment by wu-sheng** [comment]
Generally, I prefer (2) if there is no performance difference between (1) and (2) for the following reasons.
1. Instance methods are more friendly to extend, such as hierarchy override.
1. From my personal preference, the static method doesn't bring a better user experience in this case.

But, at the same time, I want to point out, 
1. There is a duplicated `dbType` parameter for the `visitor`, no matter either way. As the parsing result, you definitely have known the type, this second `dbType` could be skipped and auto-injection through the ASTTree.
1. `useCache` seems like a configuration? Do you plan to use a general configuration(even map/properties) to prepare for the extension in the future?
1. `visitorType` is really necessary? Is there another chance to get different results? Because Java doesn't recommend/support the different types of the return value, it is hard to see how to implement the new type. Could you share some ideas about this parameter?

**Comment by terrymanu** [comment]
> Generally, I prefer (2) if there is no performance difference between (1) and (2) for the following reasons.
> 
> 1. Instance methods are more friendly to extend, such as hierarchy override.
> 2. From my personal preference, the static method doesn't bring a better user experience in this case.
> 
> But, at the same time, I want to point out,
> 
> 1. There is a duplicated `dbType` parameter for the `visitor`, no matter either way. As the parsing result, you definitely have known the type, this second `dbType` could be skipped and auto-injection through the ASTTree.

Because of original SQL do not take db information, so the AST cannot know the database type. 

> 2. `useCache` seems like a configuration? Do you plan to use a general configuration(even map/properties) to prepare for the extension in the future?

`useCache` is not for configuration only, it is better to use cache if SQL with parameter markers (SELECT * FROM xxx WHERE id=?), and it is unnecessary if user use raw SQL (SELECT * FROM xxx WHERE id=1)

> 3. `visitorType` is really necessary? Is there another chance to get different results? Because Java doesn't recommend/support the different types of the return value, it is hard to see how to implement the new type. Could you share some ideas about this parameter?

`STATEMENT` is one of  `visitorType` for convert AST to SQL statement object, another `visitorType` is `FORMAT` which can support SQL formatted feature.
We may add some new visitor types in future, such as `AUDIT` which for audit whether SQL can run or not on related rule or performance issue.
The return type is use generic type <T> for now which is returned from SQL visitor generic return type.

**Comment by wu-sheng** [comment]
> Because of original SQL do not carry db information, so the AST cannot know the database type.

But the ParseTree knows as it is already a parameter of `SQLParserEngine`

> useCache is not for configuration only, it is better to use cache if SQL with parameter markers (SELECT * FROM xxx WHERE id=?), and it is unnecessary if user use raw SQL (SELECT * FROM xxx WHERE id=1)

I know the background, I was just asking about the API design, not function.

**Comment by wu-sheng** [comment]
> STATEMENT is one of visitorType for convert AST to SQL statement object, another visitorType is FORMAT which can support SQL formatted feature.
We may add some new visitor types in future, such as AUDIT which for audit whether SQL can run or not on related rule or performance issue.
The return type is use generic type for now which is returned from SQL visitor generic return type.

Same as above, I am not arguing for the functional correct. I am just saying if this API is designed for the extension, then, giving a parameter is not enough, because you can't give another parameter and add a new return type, Java doesn't support that.

**Comment by SteNicholas** [comment]
@tristaZero , I prefer the second way, because the second way is more suitable to expand according to the SQL dialect. IMO, when calling `parse()` method, the Parser should be binded with SQL dialect and known with the database type. And the interfaces of`SQLParserEngine` and `SQLVisitorEngine` in the first way isn't conducive to expansion and calling `parse()` and `visit()` method with `dbType` and  `visitorType ` makes no sense. And other parameters like `useCache ` should use config instead of single parameter.

**Comment by Arviiin** [comment]
I prefer the second way also.
but duplicated dbType  is a little strange to use.

**Comment by yu199195** [comment]
I prefer the one way, Simple and clear

**Comment by xiaoma20082008** [comment]
maybe you should reference presto's parser.
it's using method just like this:
```java
// 1. parser
SqlNode node = SqlParser.parse(sql, useCache)
// 2. visitor 
Formatter fmt = new SqlVisitor<Void,String>()
String str = fmt.accept(node);
```

**Comment by yida-lxw** [comment]
I prefer the second way mentioned above, which I think is more in line with OOP.

**Comment by guimingyue** [comment]
I prefer way 1.
`SQLParserEngine` is just a tool for parsing SQL text.

**Comment by tristaZero** [comment]
Hi,
Thanks for everyone's feedback and opinions!
Given the comments here, it looks that the second one is the most expectation. Hence, the following API is our final choice!

```java
public static void main(String[] args) {
    String dbType = "MySQL";
    String visitorType = "SQLStatement";
    boolean useCache = true;
    
    String sql1 = "select * from tb1";
    String sql2 = "select * from tb2";

    // Way2
    SQLParserEngine parser = new SQLParserEngine(dbType);
    SQLVisitorEngine visitor = new SQLVisitorEngine(dbType,  visitorType);
    
    SQLStatement result1 = visitor.visit(parser.parse(sql1,  useCache));
    SQLStatement result2 = visitor.visit(parser.parse(sql2,  useCache));
}
```

I will finish this modification ASAP and re-prepare our incoming 5.0.0-alpha release. Please wait for my updates.

Best,
Trista
