### ISSUE TITLE
sharding-proxy performance

### ISSUE THREAD

**Issue by mygitdds** [apache/shardingsphere#8527]
Since it is the agent provided, I read the source code. When I connect to MySQL, I still use the driver provided by mysql, and the overall implementation is in Java. In this way, I / O interaction with MySQL will cause thread blocking in kernel mode, which leads to low performance. I suggest go, or vertx.

**Comment by mygitdds** [comment]
There is also an asynchronous driver for MySQL on vertx

**Comment by tristaZero** [comment]
Hi @mygitdds 
I see your concern, and thanks for your issue. Could you provide some links or docs to elaborate on your idea?

**Comment by mygitdds** [comment]
When sharding proxy calls mysql, the corresponding time of MySQL will be blocked. In Java, the thread model is that a user thread corresponds to a kernel thread, so the concurrency is high. If more threads are blocked, the effective utilization rate of CPU will be very low. If vertx is used, MySQL asynchronous driver will be used, and the performance will be many orders of magnitude higher For an introduction to vertx, you can go to Google for some information. I suggest that it is important to improve the performance of sharding proxy proxy layer

**Comment by mygitdds** [comment]
@tristaZero  Vertx's performance is comparable to go。Now, with the improvement of technology, we hope to do more with less resources.

**Comment by mygitdds** [comment]
Tomorrow find time to write an article to explain the problem, and their own decision, how to solve it

**Comment by tristaZero** [comment]
@mygitdds MySQL's Vertx API, right? Yep, I like this idea! But we do not have a lot of knowledge about it, look forward to your article. :) 

English communication is necessary for GitHub, but your article in Chinese is ok. Just leave its link here.

Thanks,
Trista

**Comment by mygitdds** [comment]
https://blog.csdn.net/weixin_35997672/article/details/110920396
@tristaZero

**Comment by mygitdds** [comment]
https://blog.csdn.net/weixin_35997672/article/details/110920659
@tristaZero

**Comment by tristaZero** [comment]
Hi @mygitdds 

Thanks for sharing. Actually, I want to know more about MySQL VertX, since this issue is to discuss how to improve the performance of ShardingProxy by VertX, doesn't it? That will be great If you can also share some of your thoughts concerning ShardingProxy and MySQL vertx.

**Comment by linghengqian** [comment]
@mygitdds 

- The following are my personal views.

 - https://github.com/apache/shardingsphere/issues/13957 has taken a big step, I'm still concerned about the fact that the carrier thread is pinned due to the frequent switching of non-blocking and blocking tasks within the project. Because under Netty's event-driven model, thread blocking will greatly affect the overall performance, although this situation can put out additional thread scheduling, but if the ACTUAL USE OF JDBC pool, the cost of additional processing is too large, from God's point of view, the performance of the project is broken by a few blocking threads is difficult to stretch. 

- If we can open the Reactive link, I prefer to introduce an R2DBC Driver that implements R2DBC SPI on ShardingSphere, and only by introducing Reactor-like responsive libraries can the overall throughput be liberated. R2DBC SPI as a low-level protocol requires R2DBC Drivers to be built on top of asynchronous http and grpc clients (even RSocket that are difficult to track metadata, hilariously) because its network transport protocol is not the same as JDBC. 

- Since `ShardingSphere 5.1.2` exposes SPI for Driver, I'd like to know what you think？

**Comment by TeslaCN** [comment]
We have tried using Vert.x in ShardingSphere-Proxy. And I have tried integrate [ShardingSphere with Vert.x API](https://github.com/TeslaCN/shardingsphere-vert.x). But the improvement is not as large as expected.
Finally we found the I/O performance was not the key of performance issue. The CPU cost of calculation route, rewrite is the largest bottleneck of performance. 
At present, we are trying to reduce CPU cost of kernel. Such as https://github.com/apache/shardingsphere/issues/21223.
SInce this issue has been inactive for a while, I'm closing it for now.
