### ISSUE TITLE
`SELECT DISTINCT` SQL fails when useServerPrepStmts=true

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9127]
After #9114, the IT engine fails to run well with the `SELECT DISTINCT` SQL. It is necessary to find the cause and fix it.

**Comment by tristaZero** [comment]
@JiekerTime Are you interested in this one?

**Comment by JiekerTime** [comment]
Hi~ I will check it !

**Comment by JiekerTime** [comment]
When you use Proxy and add the useServerPrepStmts=true parameter to the URL, as long as the form of SUM() or COUNT(A+B) is used, it will cause a forced transfer exception at the bottom layer.

**Comment by JiekerTime** [comment]
When you use Proxy and add the useServerPrepStmts=true parameter to the URL, as long as the form of SUM() or COUNT(A+B) is used, it will cause a forced transfer exception at the bottom layer.
For specific proxy configuration, please refer to shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/env/db/rules.yaml
SQL statement reference "SELECT SUM(DISTINCT order_id+user_id) FROM t_order WHERE order_id <1100"
For database structure, please refer to: shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/env/db/init-sql/mysql/init.sql

----
Or you can try to run the integration test locally.

**Comment by sandynz** [comment]
I found a similar problem when PR integration test, e.g. `Integration Test / MySQL-Proxy with DB`, part of error output:
```
Error:  assertExecute[proxy: db -> MySQL -> Placeholder -> SELECT SUM(DISTINCT order_id) FROM t_order WHERE order_id < 1100](org.apache.shardingsphere.test.integration.engine.it.dql.GeneralDQLIT)  Time elapsed: 0.007 s  <<< FAILURE!
java.lang.AssertionError: 
Size of actual result set is different with size of expected dat set rows.
Expected: is <1>
     but: was <0>
```

Steps to reproduce on local environment:

1, Prepare configurations for proxy, copy config files from `shardingsphere-integration-test-suite/src/test/resrouces/docker/db/proxy/conf/` into `shardingsphere-proxy-bootstrap/src/main/resources/`
- copy `config-db.yaml` into `config-sharding.yaml`
- copy `server.yaml` into `server.yaml`

2, Update `shardingsphere-integration-test-suite/src/test/resources/env/engine-env.properties`
```
it.adapters=proxy

#it.scenarios=db,tbl,dbtbl_with_replica_query,replica_query,shadow
it.scenarios=db

#it.databases=H2,MySQL,Oracle,SQLServer,PostgreSQL
it.databases=MySQL
```

Update `shardingsphere-integration-test-suite/src/test/resources/env/db/scenario-env.properties`, `mysql` and `proxy` related configuration, e.g.
```
it.db.mysql.host=127.0.0.1
it.db.mysql.port=3306
it.db.mysql.username=root
it.db.mysql.password=

it.db.proxy.host=127.0.0.1
it.db.proxy.port=3307
```

3, Copy `org.apache.shardingsphere.proxy.Bootstrap.java` to `shardingsphere-integration-test-suite` as `ProxyBootstrapTest.java`, since `STANDARD_TEST` in `config-db.yaml` is a customized algorithm that is implemented in unit test

4, Run `ProxyBootstrapTest.java`

5, Prepare  an test client and start it, e.g. `TempTest.java`
```
public class TempTest {
    
    public static void main(String[] args) throws Exception {
        String sql;
        sql = "SELECT SUM(DISTINCT order_id) s FROM t_order WHERE order_id < 1100"; // result missed in response
//        sql = "SELECT SUM(order_id) s FROM t_order WHERE order_id < 1100"; //ok
//        sql = "SELECT COUNT(DISTINCT order_id) s FROM t_order WHERE order_id < 1100"; //ok
        String jdbcUrl = "jdbc:mysql://localhost:3307/db?useServerPrepStmts=true&serverTimezone=UTC&useSSL=false&useLocalSessionState=true&characterEncoding=utf-8";
        try (Connection connection = DriverManager.getConnection(jdbcUrl, "root", "root");
             PreparedStatement statement = connection.prepareStatement(sql)) {
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    System.out.println("c1=" + resultSet.getString(1));
                }
            }
        }
    }
}
```

**Comment by tuohai666** [comment]
Got it. Thanks for the details.
