### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by hahaxw** [apache/shardingsphere#9464]
Shardingsphere 4.1.1 has the problem of duplicate and missing data in paging query？

**Comment by menghaoranss** [comment]
Please fill in the template below：

### Which version of ShardingSphere did you use?

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
For generally, the answer is no.
But maybe some special scenario will trigger bug. Could you give us more hint to reproduce it?

**Comment by terrymanu** [comment]
No response anymore
