### ISSUE TITLE
mybatis-plus call the baseMapper.saveBatch(List<XXX> list) can't return the database auto increment id

### ISSUE THREAD

**Issue by Suny95** [apache/shardingsphere#9592]
![image](https://user-images.githubusercontent.com/26239751/109961053-70d16d80-7d24-11eb-8578-eb204431588a.png)
Until use ShardingSphere, everything is fine

**Comment by yu199195** [comment]
Hi,now we not support.

**Comment by Bin5554** [comment]
Do you support batch saving to return primary keys?

**Comment by Bin5554** [comment]
> Hi,now we not support.

Is there a solution to this situation?

**Comment by Suny95** [comment]
When will it be supported

**Comment by terrymanu** [comment]
Sorry to reply late.
mybatis-plus is the ORM framework of JDBC.
Actually, , ShardingSphere community have no time to read source codes of other ORM framework, we are focusing on JDBC(or proxy) only.
So, please do some investigate, and then we can locate about SQL and JDBC interface.

**Comment by freshgeek** [comment]
https://github.com/baomidou/mybatis-plus/issues/3207

**Comment by Tsaishichung** [comment]
> [baomidou/mybatis-plus#3207](https://github.sheincorp.cn/baomidou/mybatis-plus/issues/3207)
This issue is not related to MyBatis-Plus, but to ShardingSphere.
The key issue lies within the code segment of ShardingSpherePreparedStatement#getGeneratedKeys. 
When a single insertion is performed, it calls ShardingSpherePreparedStatement#execute. Within this method, this.cacheStatements(executionGroupContext.getInputGroups()); is executed. However, in the case of batch operations, this step is omitted, which results in the iterator being empty in ShardingSpherePreparedStatement#getGeneratedKeys.

Therefore, for non-sharded tables, single-table operations work without issues. However, batch inserts encounter a problem due to the missing caching operation in the ShardingSpherePreparedStatement, which results in an empty iterator.

**Comment by Tsaishichung** [comment]
> Sorry to reply late. mybatis-plus is the ORM framework of JDBC. Actually, , ShardingSphere community have no time to read source codes of other ORM framework, we are focusing on JDBC(or proxy) only. So, please do some investigate, and then we can locate about SQL and JDBC interface.

This issue is not related to MyBatis-Plus, but to ShardingSphere.
The key issue lies within the code segment of ShardingSpherePreparedStatement#getGeneratedKeys. When a single insertion is performed, it calls ShardingSpherePreparedStatement#execute. Within this method, this.cacheStatements(executionGroupContext.getInputGroups()); is executed. However, in the case of batch operations, this step is omitted, which results in the iterator being empty in ShardingSpherePreparedStatement#getGeneratedKeys.
Therefore, for non-sharded tables, single-table operations work without issues. However, batch inserts encounter a problem due to the missing caching operation in the ShardingSpherePreparedStatement, which results in an empty iterator.

**Comment by strongduanmu** [comment]
Hi @Tsaishichung, thank you for providing more information. Since this issue has been closed, can you resubmit a bug feedback according to the issue template?

**Comment by tnessn** [comment]
Mybatis has also encountered this problem, not just with Mybatis Plus
