### ISSUE TITLE
ORACLE SQL 'IDENTIFIER_'  rule is not correct in Literals.g4

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#9668]
## Bug Report

ORACLE SQL 'IDENTIFIER_'  rule is not correct in Literals.g4

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-sql-parser
### Expected 
IDENTIFIER_:[A-Za-z_$0-9]*?[A-Za-z_$]+?[A-Za-z_$0-9]*;
### Actual 
IDENTIFIER_:[A-Za-z]+[A-Za-z_$#0-9]*;

**Comment by wgy8283335** [comment]
@Liangda-w 
[SQL Definition Collation][Oracle]Collate the SQL definition of SET ROLE #9603

**Comment by Liangda-w** [comment]
Hi @wgy8283335, 
Your suggestion won't work properly, because if you put `PASSWORD_` before `IDENTIFIER_`, many words like for example `abc123` will be assigned `PASSWORD_` first instead of `IDENTIFIER_`, which breaks the rule for other SQL 🤔 

An example with `PASSWORD_`:
![parseTree](https://user-images.githubusercontent.com/66914151/111127913-9eb08080-8574-11eb-8bc5-f45d284942a8.png)

Why do you think `[A-Za-z_$0-9]*?[A-Za-z_$]+?[A-Za-z_$0-9]` is necessary? According to the [Oracle Database Object Naming Rules](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Database-Object-Names-and-Qualifiers.html#GUID-75337742-67FD-4EC0-985F-741C93D918DA), I think the current `IDENTIFIER_` rule is more accurate.

> Nonquoted identifiers must begin with an alphabetic character from your database character set. Quoted identifiers can begin with any character.

Please correct me if I'm thinking wrong:) Maybe we could also use the previous `IDENTIFIER_` for `password` to solve this issue.

**Comment by wgy8283335** [comment]
Good, I agree with you.
