### ISSUE TITLE
Why should we support  Oracle SQL, as Oracle has its own partitioning?

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#9926]
## Why should we support  Oracle SQL, as Oracle has its own partitioning?

Below are the VLDB and partitioning link:
https://docs.oracle.com/en/database/oracle/oracle-database/19/vldbg/partition-admin.html#GUID-F2C99CFA-1090-4A62-B452-D4E116A40A34

**Comment by tristaZero** [comment]
Hi,

Oracle partition is like the portion table of MySQL? Could it exist across different instances?

**Comment by wgy8283335** [comment]
It seems like only supporting the sharding table.

**Comment by tristaZero** [comment]
Hey, I just gave a glance at the link you mentioned. It looks this concept is similar to MySQL's partition table which can not cross different instances or servers [1]. But ShardingSphere can allow shardings to reside in different servers.
If you just had a few lookups, it is easy to get the answer instead of letting me tell you the result. 
I am welcomed to any `valuable` discussion.

[1] https://docs.oracle.com/en/database/oracle/oracle-database/19/vldbg/partition-concepts.html#GUID-DD6FC751-735F-48EF-BFC6-F636C2451701 
Note: All partitions of a partitioned object must reside in tablespaces of the same block size.
